import { Achievement, OperationType, UserSettings } from '../types';

export const XP_CONFIG = {
  TIER_1_MAX_SECONDS: 10.0,
  TIER_1_XP: 30,
  TIER_2_MAX_SECONDS: 20.0,
  TIER_2_XP: 20,
  TIER_3_MAX_SECONDS: 30.0,
  TIER_3_XP: 10,
  WRONG_OR_TIMEOUT_XP: 0,
  TIME_LIMIT_SECONDS: 30,
};

export const BASE_RANKS = [
  // 1-7: Madeira até Aço (Iniciação & Metais)
  { name: 'Madeira', color: 'from-amber-800 to-amber-950', border: 'border-amber-700', text: 'text-amber-700 dark:text-amber-400', icon: 'TreePine' },
  { name: 'Pedregulho', color: 'from-slate-600 to-slate-800', border: 'border-slate-500', text: 'text-slate-400 dark:text-slate-300', icon: 'Hexagon' },
  { name: 'Pedra', color: 'from-zinc-500 to-zinc-700', border: 'border-zinc-500', text: 'text-zinc-600 dark:text-zinc-300', icon: 'Shield' },
  { name: 'Cobre', color: 'from-orange-700 to-amber-800', border: 'border-orange-600', text: 'text-orange-600 dark:text-orange-400', icon: 'Coins' },
  { name: 'Ferro', color: 'from-slate-400 to-slate-600', border: 'border-slate-400', text: 'text-slate-600 dark:text-slate-300', icon: 'ShieldAlert' },
  { name: 'Bronze', color: 'from-amber-700 to-orange-900', border: 'border-amber-600', text: 'text-amber-600 dark:text-amber-400', icon: 'Award' },
  { name: 'Aço', color: 'from-slate-500 to-zinc-700', border: 'border-slate-400', text: 'text-slate-400 dark:text-slate-200', icon: 'Zap' },

  // 8-10: Prata até Platina (Nobreza)
  { name: 'Prata', color: 'from-slate-200 to-slate-400', border: 'border-slate-300', text: 'text-slate-500 dark:text-slate-200', icon: 'Medal' },
  { name: 'Ouro', color: 'from-yellow-400 to-amber-600', border: 'border-yellow-400', text: 'text-yellow-600 dark:text-yellow-400', icon: 'Trophy' },
  { name: 'Platina', color: 'from-teal-300 to-cyan-600', border: 'border-teal-400', text: 'text-teal-600 dark:text-teal-300', icon: 'Crown' },

  // 11-15: Gemas Preciosas & Diamante
  { name: 'Esmeralda', color: 'from-emerald-500 to-teal-700', border: 'border-emerald-500', text: 'text-emerald-500 dark:text-emerald-300', icon: 'Sparkle' },
  { name: 'Safira', color: 'from-blue-500 to-indigo-700', border: 'border-blue-500', text: 'text-blue-500 dark:text-blue-300', icon: 'Gem' },
  { name: 'Rubi', color: 'from-rose-600 to-red-800', border: 'border-rose-500', text: 'text-rose-500 dark:text-rose-300', icon: 'Flame' },
  { name: 'Ametista', color: 'from-purple-500 to-fuchsia-700', border: 'border-purple-500', text: 'text-purple-500 dark:text-purple-300', icon: 'Sparkles' },
  { name: 'Diamante', color: 'from-cyan-400 to-blue-600', border: 'border-cyan-400', text: 'text-cyan-600 dark:text-cyan-300', icon: 'Gem' },

  // 16-19: Maestria e Sobrenatural
  { name: 'Obsidiana', color: 'from-purple-900 via-stone-900 to-black', border: 'border-purple-600', text: 'text-purple-400 dark:text-purple-300', icon: 'Hexagon' },
  { name: 'Titânio', color: 'from-slate-400 via-cyan-600 to-slate-800', border: 'border-cyan-400', text: 'text-cyan-300 dark:text-cyan-100', icon: 'Shield' },
  { name: 'Mestre', color: 'from-purple-500 to-indigo-700', border: 'border-purple-500', text: 'text-purple-600 dark:text-purple-300', icon: 'Sparkles' },
  { name: 'Grão-Mestre', color: 'from-rose-500 to-red-700', border: 'border-rose-500', text: 'text-rose-600 dark:text-rose-300', icon: 'Flame' },

  // 20-23: Lendário até Celestial
  { name: 'Lendário', color: 'from-amber-400 via-rose-500 to-purple-600', border: 'border-amber-400', text: 'text-amber-500 dark:text-amber-300', icon: 'Zap' },
  { name: 'Mítico', color: 'from-fuchsia-500 to-purple-800', border: 'border-fuchsia-400', text: 'text-fuchsia-600 dark:text-fuchsia-300', icon: 'Star' },
  { name: 'Arcano', color: 'from-indigo-600 via-purple-700 to-fuchsia-900', border: 'border-indigo-400', text: 'text-indigo-400 dark:text-indigo-300', icon: 'Wand' },
  { name: 'Celestial', color: 'from-sky-300 via-indigo-400 to-pink-500', border: 'border-sky-300', text: 'text-sky-500 dark:text-sky-300', icon: 'Sun' },

  // 24-27: Estelar até Universal
  { name: 'Estelar', color: 'from-yellow-300 via-amber-500 to-orange-600', border: 'border-yellow-300', text: 'text-yellow-400 dark:text-yellow-300', icon: 'Sparkles' },
  { name: 'Cósmico', color: 'from-violet-600 via-purple-700 to-slate-900', border: 'border-violet-400', text: 'text-violet-500 dark:text-violet-300', icon: 'Orbit' },
  { name: 'Galáctico', color: 'from-emerald-400 via-teal-500 to-cyan-700', border: 'border-emerald-400', text: 'text-emerald-500 dark:text-emerald-300', icon: 'Globe' },
  { name: 'Universal', color: 'from-blue-600 via-indigo-700 to-fuchsia-800', border: 'border-indigo-400', text: 'text-indigo-500 dark:text-indigo-300', icon: 'Compass' },

  // 28-30: Transcendente, Absoluto e Infinito
  { name: 'Transcendente', color: 'from-rose-500 via-amber-400 to-cyan-500', border: 'border-rose-400', text: 'text-rose-400 dark:text-rose-200', icon: 'Atom' },
  { name: 'Absoluto', color: 'from-yellow-400 via-rose-600 to-purple-800', border: 'border-amber-300', text: 'text-amber-400 dark:text-amber-200', icon: 'Sun' },
  { name: 'Infinito', color: 'from-amber-300 via-rose-500 to-cyan-400', border: 'border-yellow-300', text: 'text-yellow-400 dark:text-yellow-300', icon: 'Infinity' },
];

export const ROMAN_NUMERALS = ['I', 'II', 'III', 'IV', 'V'];

export const DEFAULT_USER_SETTINGS: UserSettings = {
  soundEnabled: true,
  soundVolume: 0.7,
  vibrationEnabled: true,
  theme: 'dark',
  reduceMotion: false,
  dailyGoal: 10,
  timerDurationSeconds: 30,
  enabledOperations: ['addition', 'subtraction', 'multiplication', 'division'],
};

export const INITIAL_TITLES = [
  'Aprendiz Matemático',
  'Iniciante dos Números',
];

export const ACHIEVEMENTS_LIST: Achievement[] = [
  // Progression
  {
    id: 'first_calculation',
    title: 'Primeiro Passo',
    description: 'Responda sua primeira questão matemática com sucesso.',
    category: 'progression',
    icon: 'Play',
    targetMetric: 'totalCorrect',
    targetValue: 1,
    rewardTitle: 'Aprendiz Matemático',
    rewardXP: 50,
  },
  {
    id: 'solve_10',
    title: 'Aquecendo os Motores',
    description: 'Acerte 10 questões no total.',
    category: 'progression',
    icon: 'Zap',
    targetMetric: 'totalCorrect',
    targetValue: 10,
    rewardXP: 100,
  },
  {
    id: 'solve_100',
    title: 'Centena Perfeita',
    description: 'Acerte 100 questões.',
    category: 'progression',
    icon: 'Flame',
    targetMetric: 'totalCorrect',
    targetValue: 100,
    rewardTitle: 'Calculadora Humana',
    rewardXP: 300,
  },
  {
    id: 'solve_1000',
    title: 'Maratona Mental',
    description: 'Acerte 1.000 questões.',
    category: 'progression',
    icon: 'Trophy',
    targetMetric: 'totalCorrect',
    targetValue: 1000,
    rewardTitle: 'Mestre Matemático',
    rewardXP: 1000,
  },
  {
    id: 'solve_10000',
    title: 'Lenda da Aritmética',
    description: 'Acerte 10.000 questões.',
    category: 'progression',
    icon: 'Crown',
    targetMetric: 'totalCorrect',
    targetValue: 10000,
    rewardTitle: 'Lenda dos Números',
    rewardXP: 5000,
  },

  // Speed
  {
    id: 'speed_3s',
    title: 'Reflexo Relâmpago',
    description: 'Acerte uma questão em menos de 3 segundos.',
    category: 'speed',
    icon: 'Zap',
    targetMetric: 'fastestCorrectTime',
    targetValue: 3000,
    rewardTitle: 'Relâmpago',
    rewardXP: 150,
  },
  {
    id: 'speed_1s',
    title: 'Velocidade da Luz',
    description: 'Acerte uma questão em menos de 1.5 segundos.',
    category: 'speed',
    icon: 'Sparkles',
    targetMetric: 'fastestCorrectTime',
    targetValue: 1500,
    rewardTitle: 'Velocidade da Luz',
    rewardXP: 300,
  },

  // Combos & Sequências Progressivas de Acertos
  {
    id: 'streak_10_correct',
    title: 'Esquentando',
    description: 'Alcance uma sequência de 10 respostas corretas consecutivas.',
    category: 'accuracy',
    icon: 'Flame',
    targetMetric: 'maxCombo',
    targetValue: 10,
    rewardTitle: 'Esquentando',
    rewardXP: 100,
  },
  {
    id: 'streak_20_correct',
    title: 'Embalado',
    description: 'Alcance uma sequência de 20 respostas consecutivas.',
    category: 'accuracy',
    icon: 'Zap',
    targetMetric: 'maxCombo',
    targetValue: 20,
    rewardTitle: 'Embalado',
    rewardXP: 200,
  },
  {
    id: 'streak_40_correct',
    title: 'Foco Total',
    description: 'Alcance uma sequência de 40 respostas consecutivas.',
    category: 'accuracy',
    icon: 'Shield',
    targetMetric: 'maxCombo',
    targetValue: 40,
    rewardTitle: 'Foco Total',
    rewardXP: 400,
  },
  {
    id: 'streak_80_correct',
    title: 'Imparável',
    description: 'Alcance uma sequência de 80 respostas consecutivas.',
    category: 'accuracy',
    icon: 'Sparkles',
    targetMetric: 'maxCombo',
    targetValue: 80,
    rewardTitle: 'Imparável',
    rewardXP: 800,
  },
  {
    id: 'streak_160_correct',
    title: 'Máquina',
    description: 'Alcance uma sequência de 160 respostas consecutivas.',
    category: 'accuracy',
    icon: 'Target',
    targetMetric: 'maxCombo',
    targetValue: 160,
    rewardTitle: 'Máquina',
    rewardXP: 1600,
  },
  {
    id: 'streak_320_correct',
    title: 'Calculadora Humana',
    description: 'Alcance a lendária sequência de 320 respostas consecutivas.',
    category: 'accuracy',
    icon: 'Crown',
    targetMetric: 'maxCombo',
    targetValue: 320,
    rewardTitle: 'Calculadora Humana',
    rewardXP: 3200,
  },
  {
    id: 'streak_640_correct',
    title: 'Além dos Limites',
    description: 'Alcance a sequência cósmica de 640 respostas consecutivas.',
    category: 'accuracy',
    icon: 'Gem',
    targetMetric: 'maxCombo',
    targetValue: 640,
    rewardTitle: 'Além dos Limites',
    rewardXP: 6400,
  },
  {
    id: 'streak_1000_correct',
    title: 'Precisão Absoluta',
    description: 'Alcance o ápice supremo de 1.000 respostas consecutivas.',
    category: 'accuracy',
    icon: 'Trophy',
    targetMetric: 'maxCombo',
    targetValue: 1000,
    rewardTitle: 'Precisão Absoluta',
    rewardXP: 10000,
  },

  // Streaks
  {
    id: 'streak_3',
    title: 'Hábito Inicial',
    description: 'Mantenha 3 dias consecutivos de treino.',
    category: 'streak',
    icon: 'Calendar',
    targetMetric: 'currentStreak',
    targetValue: 3,
    rewardXP: 100,
  },
  {
    id: 'streak_7',
    title: 'Semana Dourada',
    description: 'Mantenha 7 dias consecutivos de treino.',
    category: 'streak',
    icon: 'CalendarCheck',
    targetMetric: 'currentStreak',
    targetValue: 7,
    rewardXP: 250,
  },
  {
    id: 'streak_30',
    title: 'Mês de Ferro',
    description: 'Mantenha 30 dias consecutivos de treino.',
    category: 'streak',
    icon: 'Award',
    targetMetric: 'currentStreak',
    targetValue: 30,
    rewardTitle: 'Foco de Aço',
    rewardXP: 1000,
  },
  {
    id: 'streak_100',
    title: 'Centenário Diário',
    description: 'Mantenha 100 dias consecutivos de treino.',
    category: 'streak',
    icon: 'Crown',
    targetMetric: 'currentStreak',
    targetValue: 100,
    rewardTitle: 'Dedicação Lendária',
    rewardXP: 3000,
  },

  // Operations Mastery
  {
    id: 'mult_master',
    title: 'Mestre da Multiplicação',
    description: 'Acerte 150 questões de multiplicação.',
    category: 'operations',
    icon: 'X',
    targetMetric: 'multCorrect',
    targetValue: 150,
    rewardTitle: 'Mestre da Multiplicação',
    rewardXP: 350,
  },
  {
    id: 'div_king',
    title: 'Rei da Divisão',
    description: 'Acerte 150 questões de divisão.',
    category: 'operations',
    icon: 'Divide',
    targetMetric: 'divCorrect',
    targetValue: 150,
    rewardTitle: 'Rei da Divisão',
    rewardXP: 350,
  },

  // Levels & Ranks
  {
    id: 'reach_level_10',
    title: 'Veterano Nível 10',
    description: 'Alcance o Nível 10 de progressão.',
    category: 'progression',
    icon: 'Star',
    targetMetric: 'level',
    targetValue: 10,
    rewardXP: 200,
  },
  {
    id: 'reach_level_50',
    title: 'Grão-Mestre Nível 50',
    description: 'Alcance o Nível 50 de progressão.',
    category: 'progression',
    icon: 'Sparkles',
    targetMetric: 'level',
    targetValue: 50,
    rewardTitle: 'Arquiteto Algorítmico',
    rewardXP: 1500,
  },
  {
    id: 'reach_rank_gold',
    title: 'Ascensão Dourada',
    description: 'Alcance a categoria Ouro I ou superior.',
    category: 'progression',
    icon: 'Trophy',
    targetMetric: 'rankTierIndex',
    targetValue: 6, // Ouro
    rewardXP: 500,
  },
  {
    id: 'reach_rank_diamond',
    title: 'Mente Diamante',
    description: 'Alcance a categoria Diamante I ou superior.',
    category: 'progression',
    icon: 'Gem',
    targetMetric: 'rankTierIndex',
    targetValue: 12, // Diamante (tier index 12)
    rewardTitle: 'Mente Diamante',
    rewardXP: 1200,
  },
  {
    id: 'reach_level_100',
    title: 'Soberano Nível 100',
    description: 'Alcance o Nível 100 de progressão global.',
    category: 'progression',
    icon: 'Crown',
    targetMetric: 'level',
    targetValue: 100,
    rewardTitle: 'Soberano Numérico',
    rewardXP: 5000,
  },
  {
    id: 'reach_rank_infinite',
    title: 'Legado Infinito',
    description: 'Alcance a prestigiada categoria Infinito.',
    category: 'progression',
    icon: 'Infinity',
    targetMetric: 'rankTierIndex',
    targetValue: 29, // Infinito (tier index 29)
    rewardTitle: 'Guardião do Infinito',
    rewardXP: 10000,
  },
  {
    id: 'to_the_infinite',
    title: 'Até o Infinito',
    description: 'Alcance o lendário Level 150 (Rank Infinito V). Conclua a jornada principal!',
    category: 'progression',
    icon: 'Sparkles',
    targetMetric: 'level',
    targetValue: 150,
    rewardTitle: 'Lenda do Infinito V',
    rewardXP: 25000,
  },
  {
    id: 'beyond_the_infinite',
    title: 'Além do Infinito',
    description: 'Alcance o Level 150 e transcenda para o sistema de Ascensão.',
    category: 'special',
    icon: 'Zap',
    targetMetric: 'level',
    targetValue: 151,
    rewardTitle: 'Ascendente Transcendental',
    rewardXP: 50000,
  },
];
