import { RankVisualConfig, RankColorTokens, RankDivisionVariant } from '../types';

/**
 * Visual Design System and Configuration for all 30 Ranks.
 * Centralized, token-driven design tokens ensuring each Rank is distinctly recognizable
 * by shape, geometry, silhouette, frame, and theme.
 */

export const DIVISION_PERCENT_WEIGHTS = [0.15, 0.17, 0.19, 0.22, 0.27];

export const RANK_VISUAL_CONFIGS: RankVisualConfig[] = [
  // 1. MADEIRA
  {
    rankId: 'madeira',
    tierIndex: 0,
    rankName: 'Madeira',
    rankSymbol: 'Escudo Entalhado',
    rankBadge: 'wooden_shield',
    rankBadgeSmall: 'badge_madeira_sm',
    rankBadgeLarge: 'badge_madeira_lg',
    rankProfileFrame: 'frame_madeira',
    rankProfileBackground: 'bg_madeira',
    rankTexture: 'wood_grain',
    rankParticleEffect: 'none',
    rankGlowEffect: 'none',
    rankAnimation: 'none',
    rankLevelUpAnimation: 'material',
    rankVisualTier: 'rustic',
    rankRarity: 'Comum',
    rankDescription: 'Todo mestre começou resolvendo a primeira conta.',
    rankColorTokens: {
      primary: '#9A5B2D',
      secondary: '#5C3A21',
      accent: '#D4A373',
      glow: 'rgba(154, 91, 45, 0.2)',
      border: '#78350F',
      frameBorder: '#8B4513',
      backgroundGradient: 'from-[#1A120B] via-[#140E08] to-[#0A0704]',
      cardGlow: 'rgba(154, 91, 45, 0.15)',
      textLight: '#FDE68A',
      textDark: '#92400E',
    },
    rankIconography: 'M12 2L4 6v6c0 5.55 3.84 10.74 8 12 4.16-1.26 8-6.45 8-12V6l-8-4z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Escudo simples em madeira rústica', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Entalhes cruzados frontais', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Borda chanfrada reforçada', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Entalhe de topo esculpido', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Ornamentos laterais em madeira talhada', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#382212', teaserText: 'O início da jornada matemática' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Emblema de Madeira',
      unlockedFrameTitle: 'Moldura de Madeira Rústica',
      unlockedThemeTitle: 'Card Rústico Inicial',
    },
    minTotalXP: 0,
    maxTotalXP: 20000,
  },

  // 2. PEDREGULHO
  {
    rankId: 'pedregulho',
    tierIndex: 1,
    rankName: 'Pedregulho',
    rankSymbol: 'Fragmento de Rocha',
    rankBadge: 'rock_fragment',
    rankBadgeSmall: 'badge_pedregulho_sm',
    rankBadgeLarge: 'badge_pedregulho_lg',
    rankProfileFrame: 'frame_pedregulho',
    rankProfileBackground: 'bg_pedregulho',
    rankTexture: 'rough_stone',
    rankParticleEffect: 'none',
    rankGlowEffect: 'none',
    rankAnimation: 'none',
    rankLevelUpAnimation: 'material',
    rankVisualTier: 'rustic',
    rankRarity: 'Comum',
    rankDescription: 'O primeiro sinal de solidez. Deixando a fragilidade para trás.',
    rankColorTokens: {
      primary: '#64748B',
      secondary: '#475569',
      accent: '#94A3B8',
      glow: 'rgba(100, 116, 139, 0.25)',
      border: '#475569',
      frameBorder: '#64748B',
      backgroundGradient: 'from-[#14181F] via-[#10141A] to-[#0A0D12]',
      cardGlow: 'rgba(100, 116, 139, 0.15)',
      textLight: '#E2E8F0',
      textDark: '#475569',
    },
    rankIconography: 'M12 2l7 4v12l-7 4-7-4V6l7-4z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Fragmento de pedra bruta', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Facetas laterais lapidadas', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Bloco duplo reforçado', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Base de rocha esculpida', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Emblema monolítico completo', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#2D3748', teaserText: 'Solidez nas primeiras operações' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Emblema de Pedregulho',
      unlockedFrameTitle: 'Moldura de Blocos de Rocha',
      unlockedThemeTitle: 'Tema Pétreo Bruto',
    },
    minTotalXP: 20000,
    maxTotalXP: 40000,
  },

  // 3. PEDRA
  {
    rankId: 'pedra',
    tierIndex: 2,
    rankName: 'Pedra',
    rankSymbol: 'Escudo de Pedra Maciça',
    rankBadge: 'carved_stone',
    rankBadgeSmall: 'badge_pedra_sm',
    rankBadgeLarge: 'badge_pedra_lg',
    rankProfileFrame: 'frame_pedra',
    rankProfileBackground: 'bg_pedra',
    rankTexture: 'carved_rock',
    rankParticleEffect: 'none',
    rankGlowEffect: 'none',
    rankAnimation: 'none',
    rankLevelUpAnimation: 'material',
    rankVisualTier: 'rustic',
    rankRarity: 'Incomum',
    rankDescription: 'Firme como um pico de montanha esculpido no tempo.',
    rankColorTokens: {
      primary: '#71717A',
      secondary: '#3F3F46',
      accent: '#A1A1AA',
      glow: 'rgba(161, 161, 170, 0.25)',
      border: '#52525B',
      frameBorder: '#71717A',
      backgroundGradient: 'from-[#18181B] via-[#121215] to-[#0A0A0C]',
      cardGlow: 'rgba(161, 161, 170, 0.15)',
      textLight: '#F4F4F5',
      textDark: '#52525B',
    },
    rankIconography: 'M12 2L3 7v10l9 5 9-5V7l-9-5zm0 4.5l5 2.8v5.4l-5 2.8-5-2.8V9.3l5-2.8z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Escudo de pedra maciça simétrico', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Fissuras decorativas talhadas', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Pico mineral central', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Placas laterais esculpidas', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Escudo da Montanha Pleno', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#3F3F46', teaserText: 'Estrutura de maestria simétrica' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Emblema de Pedra Maciça',
      unlockedFrameTitle: 'Moldura de Rocha Esculpida',
      unlockedThemeTitle: 'Tema Monolítico',
    },
    minTotalXP: 40000,
    maxTotalXP: 60000,
  },

  // 4. COBRE
  {
    rankId: 'cobre',
    tierIndex: 3,
    rankName: 'Cobre',
    rankSymbol: 'Medalhão e Martelo',
    rankBadge: 'copper_medallion',
    rankBadgeSmall: 'badge_cobre_sm',
    rankBadgeLarge: 'badge_cobre_lg',
    rankProfileFrame: 'frame_cobre',
    rankProfileBackground: 'bg_cobre',
    rankTexture: 'hammered_copper',
    rankParticleEffect: 'none',
    rankGlowEffect: 'low',
    rankAnimation: 'none',
    rankLevelUpAnimation: 'material',
    rankVisualTier: 'metallic',
    rankRarity: 'Incomum',
    rankDescription: 'A forja da mente se inicia no primeiro reflexo metálico.',
    rankColorTokens: {
      primary: '#B45309',
      secondary: '#78350F',
      accent: '#F59E0B',
      glow: 'rgba(217, 119, 6, 0.35)',
      border: '#D97706',
      frameBorder: '#B45309',
      backgroundGradient: 'from-[#241408] via-[#1A0E05] to-[#0D0702]',
      cardGlow: 'rgba(217, 119, 6, 0.2)',
      textLight: '#FEF3C7',
      textDark: '#B45309',
    },
    rankIconography: 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Medalhão em cobre martelado', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Ranhuras de forja concêntricas', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Engrenagens mecânicas internas', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Martelo forjado em alto-relevo', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Selo do Artesão de Cobre', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#78350F', teaserText: 'Primeiro escalão metálico' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Medalhão de Cobre',
      unlockedFrameTitle: 'Moldura de Cobre Polido',
      unlockedThemeTitle: 'Tema Forja de Cobre',
    },
    minTotalXP: 60000,
    maxTotalXP: 80000,
  },

  // 5. FERRO
  {
    rankId: 'ferro',
    tierIndex: 4,
    rankName: 'Ferro',
    rankSymbol: 'Escudo e Bigorna',
    rankBadge: 'iron_shield',
    rankBadgeSmall: 'badge_ferro_sm',
    rankBadgeLarge: 'badge_ferro_lg',
    rankProfileFrame: 'frame_ferro',
    rankProfileBackground: 'bg_ferro',
    rankTexture: 'brushed_iron',
    rankParticleEffect: 'subtle_sparks',
    rankGlowEffect: 'low',
    rankAnimation: 'none',
    rankLevelUpAnimation: 'material',
    rankVisualTier: 'metallic',
    rankRarity: 'Incomum',
    rankDescription: 'Moldado sob a pressão contínua do cálculo exato.',
    rankColorTokens: {
      primary: '#64748B',
      secondary: '#334155',
      accent: '#94A3B8',
      glow: 'rgba(148, 163, 184, 0.3)',
      border: '#64748B',
      frameBorder: '#94A3B8',
      backgroundGradient: 'from-[#141822] via-[#0E121A] to-[#080A0E]',
      cardGlow: 'rgba(148, 163, 184, 0.2)',
      textLight: '#F1F5F9',
      textDark: '#475569',
    },
    rankIconography: 'M12 2l8 3.5v7.5c0 6-4.5 11.5-8 13-3.5-1.5-8-7-8-13V5.5L12 2zm0 4.5L6 9v4c0 4 3 7.8 6 9 3-1.2 6-5 6-9V9l-6-2.5z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Escudo de ferro escovado robusto', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Rebites de blindagem nos cantos', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Bigorna chanfrada central', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Lâminas defensivas laterais', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Blindagem de Ferro Maciço', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#334155', teaserText: 'Blindagem robusta contra erros' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Escudo de Ferro Fundido',
      unlockedFrameTitle: 'Moldura de Ferro Escovado',
      unlockedThemeTitle: 'Tema Forja de Ferro',
    },
    minTotalXP: 80000,
    maxTotalXP: 110000,
  },

  // 6. BRONZE
  {
    rankId: 'bronze',
    tierIndex: 5,
    rankName: 'Bronze',
    rankSymbol: 'Medalhão Laurel',
    rankBadge: 'bronze_crest',
    rankBadgeSmall: 'badge_bronze_sm',
    rankBadgeLarge: 'badge_bronze_lg',
    rankProfileFrame: 'frame_bronze',
    rankProfileBackground: 'bg_bronze',
    rankTexture: 'ornate_bronze',
    rankParticleEffect: 'none',
    rankGlowEffect: 'low',
    rankAnimation: 'none',
    rankLevelUpAnimation: 'material',
    rankVisualTier: 'metallic',
    rankRarity: 'Incomum',
    rankDescription: 'O primeiro vislumbre da glória conquistada pelo próprio esforço.',
    rankColorTokens: {
      primary: '#CD7F32',
      secondary: '#8B4513',
      accent: '#FFA07A',
      glow: 'rgba(205, 127, 50, 0.35)',
      border: '#D2691E',
      frameBorder: '#CD7F32',
      backgroundGradient: 'from-[#22130A] via-[#170C06] to-[#0C0603]',
      cardGlow: 'rgba(205, 127, 50, 0.25)',
      textLight: '#FFE4E1',
      textDark: '#8B4513',
    },
    rankIconography: 'M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Medalhão bronze com borda dupla', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Ramos de louro metálicos', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Ornamentação lateral reforçada', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Brasão troféu com coroa basal', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Troféu Imperial de Bronze', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#8B4513', teaserText: 'Troféu do primeiro pódio' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Medalhão de Bronze Laurel',
      unlockedFrameTitle: 'Moldura Dupla de Bronze',
      unlockedThemeTitle: 'Tema Troféu de Bronze',
    },
    minTotalXP: 110000,
    maxTotalXP: 140000,
  },

  // 7. AÇO
  {
    rankId: 'aco',
    tierIndex: 6,
    rankName: 'Aço',
    rankSymbol: 'Escudo Lâmina',
    rankBadge: 'steel_blade',
    rankBadgeSmall: 'badge_aco_sm',
    rankBadgeLarge: 'badge_aco_lg',
    rankProfileFrame: 'frame_aco',
    rankProfileBackground: 'bg_aco',
    rankTexture: 'polished_steel',
    rankParticleEffect: 'subtle_sparks',
    rankGlowEffect: 'medium',
    rankAnimation: 'none',
    rankLevelUpAnimation: 'material',
    rankVisualTier: 'metallic',
    rankRarity: 'Raro',
    rankDescription: 'Resistência inquebrável, precisão cirúrgica a cada segundo.',
    rankColorTokens: {
      primary: '#94A3B8',
      secondary: '#475569',
      accent: '#E2E8F0',
      glow: 'rgba(226, 232, 240, 0.4)',
      border: '#94A3B8',
      frameBorder: '#CBD5E1',
      backgroundGradient: 'from-[#171D27] via-[#10151E] to-[#0A0D13]',
      cardGlow: 'rgba(226, 232, 240, 0.25)',
      textLight: '#FFFFFF',
      textDark: '#334155',
    },
    rankIconography: 'M12 2L4 6v8c0 5 3.5 9.5 8 11 4.5-1.5 8-6 8-11V6l-8-4zm0 3.5l5 2.5v5.5c0 3.5-2.5 6.8-5 7.9-2.5-1.1-5-4.4-5-7.9V8l5-2.5z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Escudo pontiagudo em aço polido', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Biselamentos afiados nas bordas', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Lâmina de corte central', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Guarda pontiaguda reforçada', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Baluarte de Aço Temperado', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#475569', teaserText: 'Precisão e reflexos afiados' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Escudo de Aço Temperado',
      unlockedFrameTitle: 'Moldura de Aço Afiado',
      unlockedThemeTitle: 'Tema Aço de Alta Precisão',
    },
    minTotalXP: 140000,
    maxTotalXP: 170000,
  },

  // 8. PRATA
  {
    rankId: 'prata',
    tierIndex: 7,
    rankName: 'Prata',
    rankSymbol: 'Estrela Refinada',
    rankBadge: 'silver_star',
    rankBadgeSmall: 'badge_prata_sm',
    rankBadgeLarge: 'badge_prata_lg',
    rankProfileFrame: 'frame_prata',
    rankProfileBackground: 'bg_prata',
    rankTexture: 'silver_sheen',
    rankParticleEffect: 'none',
    rankGlowEffect: 'medium',
    rankAnimation: 'pulse_subtle',
    rankLevelUpAnimation: 'material',
    rankVisualTier: 'noble',
    rankRarity: 'Raro',
    rankDescription: 'Elegância e clareza. Você deixou para trás o reino dos metais comuns.',
    rankColorTokens: {
      primary: '#E2E8F0',
      secondary: '#94A3B8',
      accent: '#FFFFFF',
      glow: 'rgba(255, 255, 255, 0.55)',
      border: '#CBD5E1',
      frameBorder: '#FFFFFF',
      backgroundGradient: 'from-[#1B222C] via-[#121820] to-[#0A0D12]',
      cardGlow: 'rgba(226, 232, 240, 0.3)',
      textLight: '#FFFFFF',
      textDark: '#64748B',
    },
    rankIconography: 'M12 2l2.4 7.2h7.6l-6.1 4.5 2.3 7.3-6.2-4.6-6.2 4.6 2.3-7.3-6.1-4.5h7.6z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Estrela de prata refinada simétrica', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Pontas radiantes com brilho suave', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Filigranas prateadas laterais', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Anel exterior lapidado', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Brasão de Prata Puro e Resplandecente', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#94A3B8', teaserText: 'A entrada na nobreza matemática' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Estrela de Prata Nobre',
      unlockedFrameTitle: 'Moldura de Prata Elegante',
      unlockedThemeTitle: 'Tema Nobre Prateado',
    },
    minTotalXP: 170000,
    maxTotalXP: 200000,
  },

  // 9. OURO
  {
    rankId: 'ouro',
    tierIndex: 8,
    rankName: 'Ouro',
    rankSymbol: 'Estrela Coroada com Asas',
    rankBadge: 'gold_crest',
    rankBadgeSmall: 'badge_ouro_sm',
    rankBadgeLarge: 'badge_ouro_lg',
    rankProfileFrame: 'frame_ouro',
    rankProfileBackground: 'bg_ouro',
    rankTexture: 'gold_leaf',
    rankParticleEffect: 'golden_shimmer',
    rankGlowEffect: 'high',
    rankAnimation: 'pulse_subtle',
    rankLevelUpAnimation: 'master',
    rankVisualTier: 'noble',
    rankRarity: 'Épico',
    rankDescription: 'Seu domínio já não passa despercebido. O padrão dourado da mente.',
    rankColorTokens: {
      primary: '#F59E0B',
      secondary: '#B45309',
      accent: '#FEF08A',
      glow: 'rgba(245, 158, 11, 0.65)',
      border: '#FBBF24',
      frameBorder: '#FDE047',
      backgroundGradient: 'from-[#2A1E06] via-[#1C1404] to-[#0E0A02]',
      cardGlow: 'rgba(245, 158, 11, 0.4)',
      textLight: '#FEF08A',
      textDark: '#B45309',
    },
    rankIconography: 'M12 2l3 6 6 1-4.5 4.5 1 6.5-5.5-3-5.5 3 1-6.5L3 9l6-1z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Medalhão áureo com estrela de 4 pontas', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Estrela de 6 pontas com auréola', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Asas douradas nascentes nas laterais', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Coroa ornamental superior', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Brasão Áureo Completo com Asas e Coroa', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#B45309', teaserText: 'O prestígio do ouro aguarda' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Brasão de Ouro Imperial',
      unlockedFrameTitle: 'Moldura Ornamental de Ouro Real',
      unlockedThemeTitle: 'Tema Dourado Imperial',
    },
    minTotalXP: 200000,
    maxTotalXP: 240000,
  },

  // 10. PLATINA
  {
    rankId: 'platina',
    tierIndex: 9,
    rankName: 'Platina',
    rankSymbol: 'Prisma Lapidado',
    rankBadge: 'platinum_prism',
    rankBadgeSmall: 'badge_platina_sm',
    rankBadgeLarge: 'badge_platina_lg',
    rankProfileFrame: 'frame_platina',
    rankProfileBackground: 'bg_platina',
    rankTexture: 'platinum_crystal',
    rankParticleEffect: 'crystal_float',
    rankGlowEffect: 'high',
    rankAnimation: 'pulse_subtle',
    rankLevelUpAnimation: 'gem',
    rankVisualTier: 'noble',
    rankRarity: 'Épico',
    rankDescription: 'A fusão perfeita entre a rigidez do metal e a pureza do cristal.',
    rankColorTokens: {
      primary: '#2DD4BF',
      secondary: '#0F766E',
      accent: '#CCFBF1',
      glow: 'rgba(45, 212, 191, 0.6)',
      border: '#5EEAD4',
      frameBorder: '#99F6E4',
      backgroundGradient: 'from-[#0D2422] via-[#091817] to-[#040C0B]',
      cardGlow: 'rgba(45, 212, 191, 0.35)',
      textLight: '#E6FFFA',
      textDark: '#0D9488',
    },
    rankIconography: 'M12 2L2 9l10 13 10-13-10-7zm0 3.5l7 4.9-7 9.1-7-9.1 7-4.9z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Prisma de platina geométrico', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Facetas angulares espelhadas', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Lâminas cristalinas de platina', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Halos geométricos luminosos', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Prisma de Platina Transcendental', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#0F766E', teaserText: 'Fusão geométrica de puro reflexo' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Prisma de Platina Pura',
      unlockedFrameTitle: 'Moldura de Platina Cristalizada',
      unlockedThemeTitle: 'Tema Prisma Futurista',
    },
    minTotalXP: 240000,
    maxTotalXP: 280000,
  },

  // 11. ESMERALDA
  {
    rankId: 'esmeralda',
    tierIndex: 10,
    rankName: 'Esmeralda',
    rankSymbol: 'Gema Esmeralda',
    rankBadge: 'emerald_gem',
    rankBadgeSmall: 'badge_esmeralda_sm',
    rankBadgeLarge: 'badge_esmeralda_lg',
    rankProfileFrame: 'frame_esmeralda',
    rankProfileBackground: 'bg_esmeralda',
    rankTexture: 'emerald_facets',
    rankParticleEffect: 'crystal_float',
    rankGlowEffect: 'high',
    rankAnimation: 'pulse_subtle',
    rankLevelUpAnimation: 'gem',
    rankVisualTier: 'gemstone',
    rankRarity: 'Épico',
    rankDescription: 'A joia da lucidez mental, lapidada a cada cálculo perfeito.',
    rankColorTokens: {
      primary: '#10B981',
      secondary: '#047857',
      accent: '#6EE7B7',
      glow: 'rgba(16, 185, 129, 0.6)',
      border: '#34D399',
      frameBorder: '#A7F3D0',
      backgroundGradient: 'from-[#072418] via-[#041910] to-[#020D08]',
      cardGlow: 'rgba(16, 185, 129, 0.35)',
      textLight: '#D1FAE5',
      textDark: '#047857',
    },
    rankIconography: 'M12 2L4 7v10l8 5 8-5V7l-8-5zm0 3.2l5.5 3.4-5.5 9-5.5-9 5.5-3.4z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Gema esmeralda lapidada hexagonal', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Fragmentos cristalinos cintilantes', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Brasão esmeralda facetado', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Extremidades cristalinas pontiagudas', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Esmeralda Soberana do Conhecimento', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#047857', teaserText: 'A primeira joia do prestígio' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Gema Esmeralda Lapidada',
      unlockedFrameTitle: 'Moldura de Cristais de Esmeralda',
      unlockedThemeTitle: 'Tema Esmeralda Radiante',
    },
    minTotalXP: 280000,
    maxTotalXP: 320000,
  },

  // 12. SAFIRA
  {
    rankId: 'safira',
    tierIndex: 11,
    rankName: 'Safira',
    rankSymbol: 'Safira Estelar',
    rankBadge: 'sapphire_gem',
    rankBadgeSmall: 'badge_safira_sm',
    rankBadgeLarge: 'badge_safira_lg',
    rankProfileFrame: 'frame_safira',
    rankProfileBackground: 'bg_safira',
    rankTexture: 'sapphire_depth',
    rankParticleEffect: 'crystal_float',
    rankGlowEffect: 'high',
    rankAnimation: 'pulse_subtle',
    rankLevelUpAnimation: 'gem',
    rankVisualTier: 'gemstone',
    rankRarity: 'Épico',
    rankDescription: 'Profundidade oceânica e clareza do céu noturno em um só reflexo.',
    rankColorTokens: {
      primary: '#3B82F6',
      secondary: '#1D4ED8',
      accent: '#93C5FD',
      glow: 'rgba(59, 130, 246, 0.65)',
      border: '#60A5FA',
      frameBorder: '#BFDBFE',
      backgroundGradient: 'from-[#0A192F] via-[#071222] to-[#030911]',
      cardGlow: 'rgba(59, 130, 246, 0.4)',
      textLight: '#EFF6FF',
      textDark: '#1D4ED8',
    },
    rankIconography: 'M12 2l4 6 6 4-6 4-4 6-4-6-6-4 6-4 4-6z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Safira lapidada em estrela profunda', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Ondas azuis de refração estelar', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Estrelas satélites de suporte', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Asas de cristal de safira', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Safira Celestial Plena', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#1D4ED8', teaserText: 'Clareza profunda como o oceano' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Safira Estelar Imperial',
      unlockedFrameTitle: 'Moldura de Safira do Céu Noturno',
      unlockedThemeTitle: 'Tema Safira Profunda',
    },
    minTotalXP: 320000,
    maxTotalXP: 360000,
  },

  // 13. RUBI
  {
    rankId: 'rubi',
    tierIndex: 12,
    rankName: 'Rubi',
    rankSymbol: 'Cristal Rubi Incandescente',
    rankBadge: 'ruby_gem',
    rankBadgeSmall: 'badge_rubi_sm',
    rankBadgeLarge: 'badge_rubi_lg',
    rankProfileFrame: 'frame_rubi',
    rankProfileBackground: 'bg_rubi',
    rankTexture: 'ruby_blaze',
    rankParticleEffect: 'subtle_sparks',
    rankGlowEffect: 'high',
    rankAnimation: 'pulse_subtle',
    rankLevelUpAnimation: 'gem',
    rankVisualTier: 'gemstone',
    rankRarity: 'Épico',
    rankDescription: 'Fogo mental e intensidade ardente que nunca hesita diante do tempo.',
    rankColorTokens: {
      primary: '#EF4444',
      secondary: '#B91C1C',
      accent: '#FCA5A5',
      glow: 'rgba(239, 68, 68, 0.65)',
      border: '#F87171',
      frameBorder: '#FECACA',
      backgroundGradient: 'from-[#280B0B] via-[#1A0707] to-[#0E0303]',
      cardGlow: 'rgba(239, 68, 68, 0.4)',
      textLight: '#FEF2F2',
      textDark: '#B91C1C',
    },
    rankIconography: 'M12 2l7 7-7 13L5 9l7-7zm0 4.5L7.5 9.5 12 18l4.5-8.5L12 6.5z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Gema rubi pontiaguda lapidada', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Flamas cristalinas nos vértices', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Extremidades ardentes reforçadas', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Brasão ígneo com garras de rubi', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Coração de Rubi Flamejante', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#B91C1C', teaserText: 'Intensidade e reflexo incandescente' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Cristal Rubi Incandescente',
      unlockedFrameTitle: 'Moldura de Cristais de Rubi',
      unlockedThemeTitle: 'Tema Fogo de Rubi',
    },
    minTotalXP: 360000,
    maxTotalXP: 410000,
  },

  // 14. AMETISTA
  {
    rankId: 'ametista',
    tierIndex: 13,
    rankName: 'Ametista',
    rankSymbol: 'Cristal Ametista Místico',
    rankBadge: 'amethyst_gem',
    rankBadgeSmall: 'badge_ametista_sm',
    rankBadgeLarge: 'badge_ametista_lg',
    rankProfileFrame: 'frame_ametista',
    rankProfileBackground: 'bg_ametista',
    rankTexture: 'mystic_amethyst',
    rankParticleEffect: 'crystal_float',
    rankGlowEffect: 'high',
    rankAnimation: 'pulse_subtle',
    rankLevelUpAnimation: 'gem',
    rankVisualTier: 'gemstone',
    rankRarity: 'Místico',
    rankDescription: 'O limiar da lógica pura onde a intuição matemática ganha asas.',
    rankColorTokens: {
      primary: '#A855F7',
      secondary: '#7E22CE',
      accent: '#E9D5FF',
      glow: 'rgba(168, 85, 247, 0.65)',
      border: '#C084FC',
      frameBorder: '#F3E8FF',
      backgroundGradient: 'from-[#1F0E2E] via-[#15091F] to-[#0A040F]',
      cardGlow: 'rgba(168, 85, 247, 0.4)',
      textLight: '#FAF5FF',
      textDark: '#7E22CE',
    },
    rankIconography: 'M12 2l6 4v8l-6 8-6-8V6l6-4zm0 3.8L8 8.5v5l4 5.5 4-5.5v-5L12 5.8z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Cristal ametista com facetamento místico', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Fragmentos de cristal flutuantes', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Anéis de energia mágica violeta', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Pilares de cristal suspensos', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Totem Místico de Ametista', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#7E22CE', teaserText: 'Magia dos números em cristal puro' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Cristal Místico de Ametista',
      unlockedFrameTitle: 'Moldura de Cristais Flutuantes',
      unlockedThemeTitle: 'Tema Místico Violeta',
    },
    minTotalXP: 410000,
    maxTotalXP: 460000,
  },

  // 15. DIAMANTE
  {
    rankId: 'diamante',
    tierIndex: 14,
    rankName: 'Diamante',
    rankSymbol: 'Diamante Facetado Alado',
    rankBadge: 'diamond_apex',
    rankBadgeSmall: 'badge_diamante_sm',
    rankBadgeLarge: 'badge_diamante_lg',
    rankProfileFrame: 'frame_diamante',
    rankProfileBackground: 'bg_diamante',
    rankTexture: 'diamond_facets',
    rankParticleEffect: 'crystal_float',
    rankGlowEffect: 'ultra',
    rankAnimation: 'pulse_subtle',
    rankLevelUpAnimation: 'master',
    rankVisualTier: 'gemstone',
    rankRarity: 'Místico',
    rankDescription: 'Precisão, velocidade e constância transformadas em domínio indestrutível.',
    rankColorTokens: {
      primary: '#38BDF8',
      secondary: '#0284C7',
      accent: '#E0F2FE',
      glow: 'rgba(56, 189, 248, 0.75)',
      border: '#7DD3FC',
      frameBorder: '#BAE6FD',
      backgroundGradient: 'from-[#0C2438] via-[#081826] to-[#040C13]',
      cardGlow: 'rgba(56, 189, 248, 0.5)',
      textLight: '#FFFFFF',
      textDark: '#0284C7',
    },
    rankIconography: 'M12 2l7 6-7 14L5 8l7-6zm0 3.2L7.2 8 12 17.5 16.8 8 12 5.2z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Diamante hiper-facetado lapidado', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Prismas laterais simétricos', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Asas de cristal de diamante', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Coroa de diamante puro', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Emblema de Diamante Imperial Completo', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#0284C7', teaserText: 'O ápice indestrutível do cálculo' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Diamante Hiper-Facetado',
      unlockedFrameTitle: 'Moldura de Cristais de Diamante',
      unlockedThemeTitle: 'Tema Diamante Prismático',
    },
    minTotalXP: 460000,
    maxTotalXP: 520000,
  },

  // 16. OBSIDIANA
  {
    rankId: 'obsidiana',
    tierIndex: 15,
    rankName: 'Obsidiana',
    rankSymbol: 'Fragmento de Obsidiana',
    rankBadge: 'obsidian_core',
    rankBadgeSmall: 'badge_obsidiana_sm',
    rankBadgeLarge: 'badge_obsidiana_lg',
    rankProfileFrame: 'frame_obsidiana',
    rankProfileBackground: 'bg_obsidiana',
    rankTexture: 'obsidian_sheen',
    rankParticleEffect: 'subtle_sparks',
    rankGlowEffect: 'medium',
    rankAnimation: 'pulse_subtle',
    rankLevelUpAnimation: 'master',
    rankVisualTier: 'mastery',
    rankRarity: 'Lendário',
    rankDescription: 'Forjado nas profundezas do abismo onde a concentração é absoluta.',
    rankColorTokens: {
      primary: '#9333EA',
      secondary: '#18181B',
      accent: '#C084FC',
      glow: 'rgba(147, 51, 234, 0.65)',
      border: '#7E22CE',
      frameBorder: '#A855F7',
      backgroundGradient: 'from-[#14081F] via-[#0A0410] to-[#000000]',
      cardGlow: 'rgba(147, 51, 234, 0.4)',
      textLight: '#FAF5FF',
      textDark: '#9333EA',
    },
    rankIconography: 'M12 2L2 9l4 13h12l4-13L12 2zm0 4.2l6.2 4.4-2.8 9.2H8.6L5.8 10.6 12 6.2z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Monólito negro de obsidiana polida', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Fissuras luminosas púrpuras', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Facetas escuras com reflexo espelhado', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Garras abissais de contenção', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Monólito de Obsidiana Suprema', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#581C87', teaserText: 'O vidro negro forjado na pressão' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Monólito de Obsidiana',
      unlockedFrameTitle: 'Moldura de Obsidiana Fissurada',
      unlockedThemeTitle: 'Tema Abismo de Obsidiana',
    },
    minTotalXP: 520000,
    maxTotalXP: 580000,
  },

  // 17. TITÂNIO
  {
    rankId: 'titanio',
    tierIndex: 16,
    rankName: 'Titânio',
    rankSymbol: 'Armadura Mecânica',
    rankBadge: 'titanium_armor',
    rankBadgeSmall: 'badge_titanio_sm',
    rankBadgeLarge: 'badge_titanio_lg',
    rankProfileFrame: 'frame_titanio',
    rankProfileBackground: 'bg_titanio',
    rankTexture: 'titanium_mesh',
    rankParticleEffect: 'subtle_sparks',
    rankGlowEffect: 'high',
    rankAnimation: 'none',
    rankLevelUpAnimation: 'master',
    rankVisualTier: 'mastery',
    rankRarity: 'Lendário',
    rankDescription: 'A engenharia do raciocínio em sua forma mais resistente e calculada.',
    rankColorTokens: {
      primary: '#06B6D4',
      secondary: '#334155',
      accent: '#E2E8F0',
      glow: 'rgba(6, 182, 212, 0.65)',
      border: '#22D3EE',
      frameBorder: '#A5F3FC',
      backgroundGradient: 'from-[#0B1E28] via-[#07141B] to-[#040A0E]',
      cardGlow: 'rgba(6, 182, 212, 0.4)',
      textLight: '#ECFEFF',
      textDark: '#0891B2',
    },
    rankIconography: 'M12 2l9 4v6c0 6.5-4.5 12-9 14-4.5-2-9-7.5-9-14V6l9-4zm0 4.2L6 8.5v4.2c0 4.5 3 8.5 6 10 3-1.5 6-5.5 6-10V8.5L12 6.2z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Placas simétricas de titânio aeroespacial', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Juntas mecânicas de alta pressão', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Blindagem de titânio escalonada', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Asas de exoesqueleto cibernético', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Blindagem Neural de Titânio', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#334155', teaserText: 'Engenharia de precisão cibernética' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Blindagem de Titânio',
      unlockedFrameTitle: 'Moldura de Placas Mecânicas',
      unlockedThemeTitle: 'Tema Titânio Cibernético',
    },
    minTotalXP: 580000,
    maxTotalXP: 650000,
  },

  // 18. MESTRE
  {
    rankId: 'mestre',
    tierIndex: 17,
    rankName: 'Mestre',
    rankSymbol: 'Coroa de Domínio',
    rankBadge: 'master_crest',
    rankBadgeSmall: 'badge_mestre_sm',
    rankBadgeLarge: 'badge_mestre_lg',
    rankProfileFrame: 'frame_mestre',
    rankProfileBackground: 'bg_mestre',
    rankTexture: 'master_crest',
    rankParticleEffect: 'golden_shimmer',
    rankGlowEffect: 'high',
    rankAnimation: 'pulse_subtle',
    rankLevelUpAnimation: 'master',
    rankVisualTier: 'mastery',
    rankRarity: 'Lendário',
    rankDescription: 'A mente que não apenas calcula, mas rege a matemática com maestria.',
    rankColorTokens: {
      primary: '#8B5CF6',
      secondary: '#6D28D9',
      accent: '#FDE047',
      glow: 'rgba(139, 92, 246, 0.7)',
      border: '#A78BFA',
      frameBorder: '#DDD6FE',
      backgroundGradient: 'from-[#1A1033] via-[#110A22] to-[#080511]',
      cardGlow: 'rgba(139, 92, 246, 0.45)',
      textLight: '#F5F3FF',
      textDark: '#6D28D9',
    },
    rankIconography: 'M5 16L3 5l5.5 5L12 4l3.5 6L21 5l-2 11H5zm14 3c0 .55-.45 1-1 1H6c-.55 0-1-.45-1-1v-1h14v1z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Coroa de 3 pontas com aura de maestria', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Gemas reais incrustadas na coroa', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Asas de comando imperial', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Halo de sabedoria superior', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Soberano Mestre da Aritmética', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#6D28D9', teaserText: 'A coroa do domínio supremo' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Coroa de Mestre Soberano',
      unlockedFrameTitle: 'Moldura Régia de Mestre',
      unlockedThemeTitle: 'Tema Real de Maestria',
    },
    minTotalXP: 650000,
    maxTotalXP: 720000,
  },

  // 19. GRÃO-MESTRE
  {
    rankId: 'grao_mestre',
    tierIndex: 18,
    rankName: 'Grão-Mestre',
    rankSymbol: 'Coroa Alada e Brasão',
    rankBadge: 'grandmaster_crest',
    rankBadgeSmall: 'badge_grao_mestre_sm',
    rankBadgeLarge: 'badge_grao_mestre_lg',
    rankProfileFrame: 'frame_grao_mestre',
    rankProfileBackground: 'bg_grao_mestre',
    rankTexture: 'grandmaster_weave',
    rankParticleEffect: 'golden_shimmer',
    rankGlowEffect: 'ultra',
    rankAnimation: 'pulse_subtle',
    rankLevelUpAnimation: 'master',
    rankVisualTier: 'mastery',
    rankRarity: 'Ancestral',
    rankDescription: 'No topo dos pensadores, poucos respiram o ar desta altitude.',
    rankColorTokens: {
      primary: '#E11D48',
      secondary: '#9F1239',
      accent: '#FBBF24',
      glow: 'rgba(225, 29, 72, 0.75)',
      border: '#FB7185',
      frameBorder: '#FFE4E6',
      backgroundGradient: 'from-[#2D0A14] via-[#1D060D] to-[#0E0206]',
      cardGlow: 'rgba(225, 29, 72, 0.5)',
      textLight: '#FFF1F2',
      textDark: '#9F1239',
    },
    rankIconography: 'M12 2l3 5 5-2-2 6 5 2-4 4 1 6-5-3-5 3 1-6-4-4 5-2-2-6 5 2 3-5z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Coroa régia expandida com orbe', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Orbe solar flutuante sobre a coroa', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Asas imperiais duplas flamejantes', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Flâmulas da vitória inabalável', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Trono Eterno da Grão-Maestria', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#9F1239', teaserText: 'O trono dos maiores calculadores' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Brasão do Grão-Mestre',
      unlockedFrameTitle: 'Moldura Alada Carmesim',
      unlockedThemeTitle: 'Tema Trono do Grão-Mestre',
    },
    minTotalXP: 720000,
    maxTotalXP: 800000,
  },

  // 20. LENDÁRIO
  {
    rankId: 'lendario',
    tierIndex: 19,
    rankName: 'Lendário',
    rankSymbol: 'Chama Alada Lendária',
    rankBadge: 'legendary_flame',
    rankBadgeSmall: 'badge_lendario_sm',
    rankBadgeLarge: 'badge_lendario_lg',
    rankProfileFrame: 'frame_lendario',
    rankProfileBackground: 'bg_lendario',
    rankTexture: 'legendary_flame',
    rankParticleEffect: 'golden_shimmer',
    rankGlowEffect: 'ultra',
    rankAnimation: 'pulse_subtle',
    rankLevelUpAnimation: 'mythic',
    rankVisualTier: 'mythical',
    rankRarity: 'Ancestral',
    rankDescription: 'Poucos chegam até aqui. Seu nome passa a ecoar entre as lendas.',
    rankColorTokens: {
      primary: '#F97316',
      secondary: '#D946EF',
      accent: '#FEF08A',
      glow: 'rgba(249, 115, 22, 0.8)',
      border: '#FB923C',
      frameBorder: '#FED7AA',
      backgroundGradient: 'from-[#2A1004] via-[#1B0A1C] to-[#0A040F]',
      cardGlow: 'rgba(249, 115, 22, 0.55)',
      textLight: '#FFF7ED',
      textDark: '#C2410C',
    },
    rankIconography: 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Fênix nascente rompendo bordas clássicas', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Asas flamejantes de fogo cósmico', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Chama solar tríplice incandescente', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Olho da sabedoria ancestral', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Emblema Lendário Imperecível', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#EA580C', teaserText: 'A fênix ancestral que nunca se apaga' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Emblema da Fênix Lendária',
      unlockedFrameTitle: 'Moldura de Asas Flamejantes',
      unlockedThemeTitle: 'Tema Fênix Lendária',
    },
    minTotalXP: 800000,
    maxTotalXP: 880000,
  },

  // 21. MÍTICO
  {
    rankId: 'mitico',
    tierIndex: 20,
    rankName: 'Mítico',
    rankSymbol: 'Núcleo Místico e Runas',
    rankBadge: 'mythic_eye',
    rankBadgeSmall: 'badge_mitico_sm',
    rankBadgeLarge: 'badge_mitico_lg',
    rankProfileFrame: 'frame_mitico',
    rankProfileBackground: 'bg_mitico',
    rankTexture: 'mythic_runes',
    rankParticleEffect: 'arcane_orbits',
    rankGlowEffect: 'ultra',
    rankAnimation: 'orbit_spin',
    rankLevelUpAnimation: 'mythic',
    rankVisualTier: 'mythical',
    rankRarity: 'Celestial',
    rankDescription: 'Onde o cálculo toca o inexplicável e as fórmulas viram magia pura.',
    rankColorTokens: {
      primary: '#D946EF',
      secondary: '#701A75',
      accent: '#F5D0FE',
      glow: 'rgba(217, 70, 239, 0.8)',
      border: '#E879F9',
      frameBorder: '#FAE8FF',
      backgroundGradient: 'from-[#240628] via-[#17041A] to-[#0A020B]',
      cardGlow: 'rgba(217, 70, 239, 0.55)',
      textLight: '#FDF4FF',
      textDark: '#A21CAF',
    },
    rankIconography: 'M12 2L4 9l3 12h10l3-12-8-7zm0 4l5.3 4.7-2 8.3H8.7l-2-8.3L12 6z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Núcleo místico com runas geométricas', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Anel rúnico em rotação suave', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Triângulo sagrado da verdade matemática', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Glifos ancestrais luminosos', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Círculo Mítico Eterno', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#701A75', teaserText: 'O limiar da geometria sagrada' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Núcleo Rúnico Mítico',
      unlockedFrameTitle: 'Moldura de Runas Místicas',
      unlockedThemeTitle: 'Tema Rúnico Mágico',
    },
    minTotalXP: 880000,
    maxTotalXP: 970000,
  },

  // 22. ARCANO
  {
    rankId: 'arcano',
    tierIndex: 21,
    rankName: 'Arcano',
    rankSymbol: 'Sigilo Arcano e Anéis',
    rankBadge: 'arcane_sigil',
    rankBadgeSmall: 'badge_arcano_sm',
    rankBadgeLarge: 'badge_arcano_lg',
    rankProfileFrame: 'frame_arcano',
    rankProfileBackground: 'bg_arcano',
    rankTexture: 'arcane_sigil',
    rankParticleEffect: 'arcane_orbits',
    rankGlowEffect: 'ultra',
    rankAnimation: 'orbit_spin',
    rankLevelUpAnimation: 'mythic',
    rankVisualTier: 'mythical',
    rankRarity: 'Celestial',
    rankDescription: 'Os segredos mais profundos dos números agora dançam ao seu redor.',
    rankColorTokens: {
      primary: '#6366F1',
      secondary: '#312E81',
      accent: '#67E8F9',
      glow: 'rgba(99, 102, 241, 0.85)',
      border: '#818CF8',
      frameBorder: '#C7D2FE',
      backgroundGradient: 'from-[#121338] via-[#0B0C24] to-[#050612]',
      cardGlow: 'rgba(99, 102, 241, 0.6)',
      textLight: '#EEF2FF',
      textDark: '#4338CA',
    },
    rankIconography: 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm0-14c-3.31 0-6 2.69-6 6s2.69 6 6 6 6-2.69 6-6-2.69-6-6-6z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Sigilo geométrico com núcleo energético', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Primeiro anel orbital em movimento', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Segundo anel orbital contra-rotativo', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Nodos energéticos nas intersecções', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Convergência Arcana Suprema', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#312E81', teaserText: 'Anéis de energia em rotação viva' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Sigilo Arcano Supremo',
      unlockedFrameTitle: 'Moldura de Anéis Orbitais',
      unlockedThemeTitle: 'Tema Sigilo Arcano',
    },
    minTotalXP: 970000,
    maxTotalXP: 1060000,
  },

  // 23. CELESTIAL
  {
    rankId: 'celestial',
    tierIndex: 22,
    rankName: 'Celestial',
    rankSymbol: 'Estrela Celestial e Halo',
    rankBadge: 'celestial_star',
    rankBadgeSmall: 'badge_celestial_sm',
    rankBadgeLarge: 'badge_celestial_lg',
    rankProfileFrame: 'frame_celestial',
    rankProfileBackground: 'bg_celestial',
    rankTexture: 'celestial_nebula',
    rankParticleEffect: 'cosmic_nebula',
    rankGlowEffect: 'ultra',
    rankAnimation: 'orbit_spin',
    rankLevelUpAnimation: 'cosmic',
    rankVisualTier: 'cosmic',
    rankRarity: 'Celestial',
    rankDescription: 'A ordem das estrelas espelhada na precisão de cada sinapse.',
    rankColorTokens: {
      primary: '#38BDF8',
      secondary: '#1E3A8A',
      accent: '#FDE047',
      glow: 'rgba(56, 189, 248, 0.9)',
      border: '#7DD3FC',
      frameBorder: '#E0F2FE',
      backgroundGradient: 'from-[#0C223A] via-[#071626] to-[#030A12]',
      cardGlow: 'rgba(56, 189, 248, 0.65)',
      textLight: '#F0F9FF',
      textDark: '#0369A1',
    },
    rankIconography: 'M12 2l2.8 6.6 7.2.6-5.4 4.8 1.6 7L12 17.4 5.8 21l1.6-7-5.4-4.8 7.2-.6L12 2z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Estrela solar com halo luminoso', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Halo duplo com pó de estrelas', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Constelações circundantes alinhadas', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Aurora celestial radiante', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Astro Celeste Supremo', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#1E3A8A', teaserText: 'A luz pura das estrelas celestes' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Astro Celestial Supremo',
      unlockedFrameTitle: 'Moldura de Estrelas Celestes',
      unlockedThemeTitle: 'Tema Luz Celestial',
    },
    minTotalXP: 1060000,
    maxTotalXP: 1160000,
  },

  // 24. ESTELAR
  {
    rankId: 'estelar',
    tierIndex: 23,
    rankName: 'Estelar',
    rankSymbol: 'Estrela Múltipla Estelar',
    rankBadge: 'stellar_cluster',
    rankBadgeSmall: 'badge_estelar_sm',
    rankBadgeLarge: 'badge_estelar_lg',
    rankProfileFrame: 'frame_estelar',
    rankProfileBackground: 'bg_estelar',
    rankTexture: 'stellar_dust',
    rankParticleEffect: 'cosmic_nebula',
    rankGlowEffect: 'ultra',
    rankAnimation: 'orbit_spin',
    rankLevelUpAnimation: 'cosmic',
    rankVisualTier: 'cosmic',
    rankRarity: 'Celestial',
    rankDescription: 'Um sistema inteiro de pensamentos orbitando a verdade matemática.',
    rankColorTokens: {
      primary: '#F59E0B',
      secondary: '#B45309',
      accent: '#FEF08A',
      glow: 'rgba(245, 158, 11, 0.9)',
      border: '#FBBF24',
      frameBorder: '#FEF3C7',
      backgroundGradient: 'from-[#2B1B04] via-[#1B1102] to-[#0D0801]',
      cardGlow: 'rgba(245, 158, 11, 0.65)',
      textLight: '#FFFBEB',
      textDark: '#B45309',
    },
    rankIconography: 'M12 2l2 5 5 2-5 2-2 5-2-5-5-2 5-2 2-5zm0 6l-1 2.5-2.5 1 2.5 1 1 2.5 1-2.5 2.5-1-2.5-1L12 8z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Estrela binária com órbitas circulares', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: '3 astros orbitais alinhados', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: '4 astros com marcas estelares', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: '5 astros em equilíbrio hiperbólico', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Sistema Estelar Pleno de 5 Estrelas', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#B45309', teaserText: 'O balé dos sistemas estelares' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Sistema Estelar Quíntuplo',
      unlockedFrameTitle: 'Moldura de Órbitas Estelares',
      unlockedThemeTitle: 'Tema Supernova Estelar',
    },
    minTotalXP: 1160000,
    maxTotalXP: 1260000,
  },

  // 25. CÓSMICO
  {
    rankId: 'cosmico',
    tierIndex: 24,
    rankName: 'Cósmico',
    rankSymbol: 'Núcleo Cósmico & Galáxia',
    rankBadge: 'cosmic_singularity',
    rankBadgeSmall: 'badge_cosmico_sm',
    rankBadgeLarge: 'badge_cosmico_lg',
    rankProfileFrame: 'frame_cosmico',
    rankProfileBackground: 'bg_cosmico',
    rankTexture: 'cosmic_vortex',
    rankParticleEffect: 'cosmic_nebula',
    rankGlowEffect: 'cosmic_pulsar',
    rankAnimation: 'nebula_flow',
    rankLevelUpAnimation: 'cosmic',
    rankVisualTier: 'cosmic',
    rankRarity: 'Transcendente',
    rankDescription: 'A densidade infinita do conhecimento colapsada em reflexos imediatos.',
    rankColorTokens: {
      primary: '#8B5CF6',
      secondary: '#1E1B4B',
      accent: '#E9D5FF',
      glow: 'rgba(139, 92, 246, 0.95)',
      border: '#A78BFA',
      frameBorder: '#EDE9FE',
      backgroundGradient: 'from-[#190C36] via-[#100724] to-[#06020E]',
      cardGlow: 'rgba(139, 92, 246, 0.7)',
      textLight: '#F5F3FF',
      textDark: '#6D28D9',
    },
    rankIconography: 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 15c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Núcleo cósmico com horizonte de eventos', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Anel de acreção luminosa', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Jatos de plasma cósmico polares', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Singularidade geométrica curvando a luz', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Senhor do Vórtice Cósmico', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#1E1B4B', teaserText: 'A gravidade irresistível do saber' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Singularidade Cósmica',
      unlockedFrameTitle: 'Moldura de Vórtice Gravitacional',
      unlockedThemeTitle: 'Tema Nebulosa Cósmica',
    },
    minTotalXP: 1260000,
    maxTotalXP: 1380000,
  },

  // 26. GALÁCTICO
  {
    rankId: 'galactico',
    tierIndex: 25,
    rankName: 'Galáctico',
    rankSymbol: 'Espiral Galáctica Vórtice',
    rankBadge: 'galactic_spiral',
    rankBadgeSmall: 'badge_galactico_sm',
    rankBadgeLarge: 'badge_galactico_lg',
    rankProfileFrame: 'frame_galactico',
    rankProfileBackground: 'bg_galactico',
    rankTexture: 'galactic_spiral',
    rankParticleEffect: 'cosmic_nebula',
    rankGlowEffect: 'cosmic_pulsar',
    rankAnimation: 'nebula_flow',
    rankLevelUpAnimation: 'cosmic',
    rankVisualTier: 'transcendent',
    rankRarity: 'Transcendente',
    rankDescription: 'Bilhões de possibilidades navegadas com a certeza de um único caminho.',
    rankColorTokens: {
      primary: '#10B981',
      secondary: '#064E3B',
      accent: '#6EE7B7',
      glow: 'rgba(16, 185, 129, 0.95)',
      border: '#34D399',
      frameBorder: '#D1FAE5',
      backgroundGradient: 'from-[#05261C] via-[#031812] to-[#010B08]',
      cardGlow: 'rgba(16, 185, 129, 0.7)',
      textLight: '#ECFDF5',
      textDark: '#047857',
    },
    rankIconography: 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 14.93c-2.82.4-5.06-1.84-4.66-4.66.27-1.92 1.82-3.47 3.73-3.73 2.82-.4 5.06 1.84 4.66 4.66-.27 1.92-1.82 3.47-3.73 3.73z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Núcleo espiral com braços estelares', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: '2 braços estelares rompendo o badge', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: '4 braços galácticos com aglomerados', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Aglomerados globulares satélites', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Galáxia Viva Monumental Completa', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#064E3B', teaserText: 'Espiral de bilhões de sinapses' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Espiral Galáctica Viva',
      unlockedFrameTitle: 'Moldura de Braços Galácticos',
      unlockedThemeTitle: 'Tema Aurora Galáctica',
    },
    minTotalXP: 1380000,
    maxTotalXP: 1500000,
  },

  // 27. UNIVERSAL
  {
    rankId: 'universal',
    tierIndex: 26,
    rankName: 'Universal',
    rankSymbol: 'Esfera Universal com Halo Duplo',
    rankBadge: 'universal_sphere',
    rankBadgeSmall: 'badge_universal_sm',
    rankBadgeLarge: 'badge_universal_lg',
    rankProfileFrame: 'frame_universal',
    rankProfileBackground: 'bg_universal',
    rankTexture: 'universal_portal',
    rankParticleEffect: 'cosmic_nebula',
    rankGlowEffect: 'cosmic_pulsar',
    rankAnimation: 'nebula_flow',
    rankLevelUpAnimation: 'cosmic',
    rankVisualTier: 'transcendent',
    rankRarity: 'Transcendente',
    rankDescription: 'Todas as equações do cosmos convergem na ponta dos seus dedos.',
    rankColorTokens: {
      primary: '#2563EB',
      secondary: '#172554',
      accent: '#FDE047',
      glow: 'rgba(37, 99, 235, 1)',
      border: '#60A5FA',
      frameBorder: '#DBEAFE',
      backgroundGradient: 'from-[#0B1E40] via-[#071328] to-[#030914]',
      cardGlow: 'rgba(37, 99, 235, 0.75)',
      textLight: '#EFF6FF',
      textDark: '#1D4ED8',
    },
    rankIconography: 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Portal esférico com halo dimensional', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Halo duplo com esferas satélites', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Cordas cósmicas entrelaçadas', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Convergência de múltiplos universos', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Arquiteto Universal da Realidade', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#172554', teaserText: 'O portal da escala universal' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Portal Universal Cósmico',
      unlockedFrameTitle: 'Moldura de Portal Multiversal',
      unlockedThemeTitle: 'Tema Tecido Universal',
    },
    minTotalXP: 1500000,
    maxTotalXP: 1630000,
  },

  // 28. TRANSCENDENTE
  {
    rankId: 'transcendente',
    tierIndex: 27,
    rankName: 'Transcendente',
    rankSymbol: 'Energia Transcendente Abstrata',
    rankBadge: 'transcendent_energy',
    rankBadgeSmall: 'badge_transcendente_sm',
    rankBadgeLarge: 'badge_transcendente_lg',
    rankProfileFrame: 'frame_transcendente',
    rankProfileBackground: 'bg_transcendente',
    rankTexture: 'transcendent_matrix',
    rankParticleEffect: 'infinite_energy',
    rankGlowEffect: 'cosmic_pulsar',
    rankAnimation: 'infinite_flux',
    rankLevelUpAnimation: 'infinite',
    rankVisualTier: 'transcendent',
    rankRarity: 'Transcendente',
    rankDescription: 'Além da matéria, além do tempo. A matemática em seu estado primordial.',
    rankColorTokens: {
      primary: '#F43F5E',
      secondary: '#881337',
      accent: '#38BDF8',
      glow: 'rgba(244, 63, 94, 1)',
      border: '#FB7185',
      frameBorder: '#FFE4E6',
      backgroundGradient: 'from-[#2E0713] via-[#1D040C] to-[#0C0205]',
      cardGlow: 'rgba(244, 63, 94, 0.8)',
      textLight: '#FFF1F2',
      textDark: '#BE123C',
    },
    rankIconography: 'M12 2l8 4.5v9L12 20l-8-4.5v-9L12 2zm0 3.2L6 8.5v7l6 3.3 6-3.3v-7L12 5.2z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Forma geométrica não-euclidiana flutuante', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Tesselas quânticas de energia pura', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Camadas dimensionais fragmentadas', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Matriz multidimensional aberta', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Consciência Pura Transcendente', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#881337', teaserText: 'Geometria pura além da matéria' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Nexus Transcendente Primordial',
      unlockedFrameTitle: 'Moldura de Energia Fragmentada',
      unlockedThemeTitle: 'Tema Matriz Quântica',
    },
    minTotalXP: 1630000,
    maxTotalXP: 1780000,
  },

  // 29. ABSOLUTO
  {
    rankId: 'absoluto',
    tierIndex: 28,
    rankName: 'Absoluto',
    rankSymbol: 'Núcleo Absoluto & Partículas',
    rankBadge: 'absolute_core',
    rankBadgeSmall: 'badge_absoluto_sm',
    rankBadgeLarge: 'badge_absoluto_lg',
    rankProfileFrame: 'frame_absoluto',
    rankProfileBackground: 'bg_absoluto',
    rankTexture: 'absolute_core',
    rankParticleEffect: 'infinite_energy',
    rankGlowEffect: 'cosmic_pulsar',
    rankAnimation: 'infinite_flux',
    rankLevelUpAnimation: 'infinite',
    rankVisualTier: 'infinite',
    rankRarity: 'Infinito',
    rankDescription: 'O limiar da perfeição. Menos de um em um milhão contemplará este selo.',
    rankColorTokens: {
      primary: '#EAB308',
      secondary: '#991B1B',
      accent: '#FFFFFF',
      glow: 'rgba(234, 179, 8, 1)',
      border: '#FDE047',
      frameBorder: '#FEF08A',
      backgroundGradient: 'from-[#2B1B04] via-[#170505] to-[#040101]',
      cardGlow: 'rgba(234, 179, 8, 0.85)',
      textLight: '#FEFCE8',
      textDark: '#A16207',
    },
    rankIconography: 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm0-15c-3.86 0-7 3.14-7 7s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm0 11c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Monólito absoluto simples e imutável', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Selos cardinais de autoridade pura', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Tríplice auréola quântica cintilante', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Emanações de plasma dourado puro', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Monólito Absoluto Pleno da Existência', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#991B1B', teaserText: 'O ápice inquestionável da mente' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Monólito do Absoluto',
      unlockedFrameTitle: 'Moldura do Selo Supremo',
      unlockedThemeTitle: 'Tema Perfeição Absoluta',
    },
    minTotalXP: 1780000,
    maxTotalXP: 1940000,
  },

  // 30. INFINITO
  {
    rankId: 'infinito',
    tierIndex: 29,
    rankName: 'Infinito',
    rankSymbol: 'Emblema Infinito Geométrico Original',
    rankBadge: 'infinite_nexus',
    rankBadgeSmall: 'badge_infinito_sm',
    rankBadgeLarge: 'badge_infinito_lg',
    rankProfileFrame: 'frame_infinito',
    rankProfileBackground: 'bg_infinito',
    rankTexture: 'infinite_nexus',
    rankParticleEffect: 'infinite_energy',
    rankGlowEffect: 'cosmic_pulsar',
    rankAnimation: 'infinite_flux',
    rankLevelUpAnimation: 'infinite',
    rankVisualTier: 'infinite',
    rankRarity: 'Infinito',
    rankDescription: 'O fim da jornada era apenas o começo. Bem-vindo à eternidade dos números.',
    rankColorTokens: {
      primary: '#F59E0B',
      secondary: '#EC4899',
      accent: '#06B6D4',
      glow: 'rgba(245, 158, 11, 1)',
      border: '#FBBF24',
      frameBorder: '#FDE047',
      backgroundGradient: 'from-[#2E1605] via-[#210928] to-[#041724]',
      cardGlow: 'rgba(245, 158, 11, 0.9)',
      textLight: '#FFFFFF',
      textDark: '#D97706',
    },
    rankIconography: 'M18.6 6.62c-1.44 0-2.8.56-3.77 1.5l-2.83 2.76-2.83-2.76c-.97-.94-2.33-1.5-3.77-1.5-2.98 0-5.4 2.42-5.4 5.38 0 2.96 2.42 5.38 5.4 5.38 1.44 0 2.8-.56 3.77-1.5l2.83-2.76 2.83 2.76c.97.94 2.33 1.5 3.77 1.5 2.98 0 5.4-2.42 5.4-5.38 0-2.96-2.42-5.38-5.4-5.38zm-13.2 8.76c-1.88 0-3.4-1.52-3.4-3.38s1.52-3.38 3.4-3.38c.91 0 1.77.35 2.38.96l2.42 2.42-2.42 2.42c-.61.61-1.47.96-2.38.96zm13.2 0c-.91 0-1.77-.35-2.38-.96l-2.42-2.42 2.42-2.42c.61-.61 1.47-.96 2.38-.96 1.88 0 3.4 1.52 3.4 3.38s-1.52 3.38-3.4 3.38z',
    rankDivisionVariants: [
      { division: 1, roman: 'I', addedDetailsDescription: 'Arcos interligados geométricos com núcleo estelar', xpThresholdPercent: 0.15 },
      { division: 2, roman: 'II', addedDetailsDescription: 'Estrela central de fusão estelar e anéis concêntricos', xpThresholdPercent: 0.17 },
      { division: 3, roman: 'III', addedDetailsDescription: 'Asas de pura energia dimensional', xpThresholdPercent: 0.19 },
      { division: 4, roman: 'IV', addedDetailsDescription: 'Coroa de constelações em fluxo perpétuo', xpThresholdPercent: 0.22 },
      { division: 5, roman: 'V', addedDetailsDescription: 'Nexus do Infinito Supremo — Conclusão da Jornada & Ascensão Desbloqueada', xpThresholdPercent: 0.27 },
    ],
    rankLockedPreview: { silhouetteColor: '#7C2D12', teaserText: 'O destino supremo de todo pensador' },
    rankUnlockedPreview: {
      unlockedBadgeTitle: 'Nexus do Infinito Supremo',
      unlockedFrameTitle: 'Moldura Suprema do Infinito',
      unlockedThemeTitle: 'Tema Eternidade do Infinito',
    },
    minTotalXP: 1940000,
    maxTotalXP: 2100000,
  },
];

/**
 * Returns the exact visual configuration for any rank identifier or tier index.
 */
export function getRankVisualConfig(identifier: string | number): RankVisualConfig {
  if (typeof identifier === 'number') {
    const safeIndex = Math.min(RANK_VISUAL_CONFIGS.length - 1, Math.max(0, identifier));
    return RANK_VISUAL_CONFIGS[safeIndex];
  }

  const normalized = identifier.toLowerCase().trim();
  const found = RANK_VISUAL_CONFIGS.find(
    (c) => c.rankId === normalized || c.rankName.toLowerCase() === normalized
  );

  return found || RANK_VISUAL_CONFIGS[0];
}

/**
 * Ascension visual generator for levels beyond 150
 */
export function getAscensionVisualConfig(ascensionLevel: number, division: number = 1): RankVisualConfig {
  const baseInfinite = RANK_VISUAL_CONFIGS[29]; // Infinito
  return {
    ...baseInfinite,
    rankId: `ascensao_${ascensionLevel}`,
    rankName: `Infinito ∞${ascensionLevel}`,
    rankSymbol: `Nexus Infinito com ${ascensionLevel} Estrela(s) de Ascensão`,
    rankRarity: 'Infinito',
    rankDescription: `Ascensão Grau ${ascensionLevel}. A maestria que continua ultrapassando os limites do universo.`,
    rankColorTokens: {
      ...baseInfinite.rankColorTokens,
      primary: '#FBBF24',
      accent: '#F43F5E',
      glow: 'rgba(251, 191, 36, 1)',
    },
  };
}
