import { OperationType, GameMode, SubjectCategory, SubjectId } from '../types';

export interface SubjectTopic {
  id: string;
  subjectId: SubjectId;
  name: string;
  description: string;
  order: number;
  weight: number; // For exam relevance (1 to 5)
  iconName?: string;
}

export interface SubjectDefinition {
  id: SubjectId;
  name: string;
  shortName: string;
  description: string;
  category: SubjectCategory;
  color: string; // Tailwind color name e.g. "blue", "emerald", "amber"
  accentColorHex: string; // e.g. "#3B82F6"
  badgeBg: string;
  badgeBorder: string;
  badgeText: string;
  gradient: string;
  iconName: string;
  topics: SubjectTopic[];
  examWeights?: Record<string, number>; // e.g. { FATEC: 5, ENEM: 4, FUVEST: 5 }
}

export const SUBJECTS_CONFIG: Record<SubjectId, SubjectDefinition> = {
  matematica: {
    id: 'matematica',
    name: 'Matemática',
    shortName: 'Mat',
    description: 'Cálculo, álgebra, geometria, funções, trigonometria e raciocínio analítico.',
    category: 'exatas',
    color: 'amber',
    accentColorHex: '#F59E0B',
    badgeBg: 'bg-amber-500/10',
    badgeBorder: 'border-amber-500/30',
    badgeText: 'text-amber-400',
    gradient: 'from-amber-500/20 via-orange-500/10 to-transparent',
    iconName: 'Calculator',
    topics: [
      { id: 'aritmetica_basica', subjectId: 'matematica', name: 'Aritmética e Operações', description: 'Adição, subtração, multiplicação, divisão e propriedades', order: 1, weight: 5 },
      { id: 'fracoes_decimais', subjectId: 'matematica', name: 'Frações e Decimais', description: 'Operações fracionárias, dízimas e simplificação', order: 2, weight: 4 },
      { id: 'razao_proporcao', subjectId: 'matematica', name: 'Razão e Proporção', description: 'Grandezas direta e inversamente proporcionais, escalas', order: 3, weight: 5 },
      { id: 'porcentagem', subjectId: 'matematica', name: 'Porcentagem e Juros', description: 'Aumentos, descontos, juros simples e compostos', order: 4, weight: 5 },
      { id: 'regra_de_tres', subjectId: 'matematica', name: 'Regra de Três', description: 'Regra de três simples e composta', order: 5, weight: 4 },
      { id: 'equacoes_inequacoes', subjectId: 'matematica', name: 'Equações e Inequações', description: '1º e 2º graus, sistemas lineares e resolução gráfica', order: 6, weight: 4 },
      { id: 'funcoes', subjectId: 'matematica', name: 'Funções (Afim, Quadrática, Exponencial)', description: 'Domínio, imagem, raízes e gráficos', order: 7, weight: 5 },
      { id: 'geometria_plana', subjectId: 'matematica', name: 'Geometria Plana', description: 'Áreas, perímetros, semelhança e Teorema de Pitágoras', order: 8, weight: 5 },
      { id: 'geometria_espacial', subjectId: 'matematica', name: 'Geometria Espacial', description: 'Prismas, pirâmides, cilindros, cones e esferas', order: 9, weight: 4 },
      { id: 'trigonometria', subjectId: 'matematica', name: 'Trigonometria', description: 'Triângulo retângulo, ciclo trigonométrico e identidades', order: 10, weight: 4 },
      { id: 'probabilidade_estatistica', subjectId: 'matematica', name: 'Probabilidade e Estatística', description: 'Média, mediana, moda, desvio e chances', order: 11, weight: 5 },
      { id: 'analise_combinatoria', subjectId: 'matematica', name: 'Análise Combinatória', description: 'Princípio fundamental, arranjos, permutações e combinações', order: 12, weight: 4 },
      { id: 'progressoes', subjectId: 'matematica', name: 'Progressões (PA e PG)', description: 'Termo geral, soma dos termos e aplicações', order: 13, weight: 4 },
      { id: 'logaritmos', subjectId: 'matematica', name: 'Logaritmos', description: 'Definição, propriedades operatórias e equações', order: 14, weight: 3 },
      { id: 'geometria_analitica', subjectId: 'matematica', name: 'Geometria Analítica', description: 'Ponto, reta, distância e circunferência', order: 15, weight: 3 },
      { id: 'matematica_financeira', subjectId: 'matematica', name: 'Matemática Financeira', description: 'Amortização, taxa de retorno e inflação', order: 16, weight: 3 },
    ],
  },
  fisica: {
    id: 'fisica',
    name: 'Física',
    shortName: 'Fís',
    description: 'Mecânica, termologia, óptica, ondulatória, eletricidade e magnetismo.',
    category: 'exatas',
    color: 'cyan',
    accentColorHex: '#06B6D4',
    badgeBg: 'bg-cyan-500/10',
    badgeBorder: 'border-cyan-500/30',
    badgeText: 'text-cyan-400',
    gradient: 'from-cyan-500/20 via-blue-500/10 to-transparent',
    iconName: 'Zap',
    topics: [
      { id: 'cinematica', subjectId: 'fisica', name: 'Cinemática Escalar e Vetorial', description: 'Velocidade média, MRU, MRUV e lançamentos', order: 1, weight: 5 },
      { id: 'dinamica_newton', subjectId: 'fisica', name: 'Dinâmica e Leis de Newton', description: 'Forças, atrito, plano inclinado e resultante centrípeta', order: 2, weight: 5 },
      { id: 'trabalho_energia', subjectId: 'fisica', name: 'Trabalho, Potência e Energia', description: 'Conservação de energia mecânica e rendimento', order: 3, weight: 5 },
      { id: 'impulso_movimento', subjectId: 'fisica', name: 'Impulso e Quantidade de Movimento', description: 'Colisões e conservação do momento linear', order: 4, weight: 4 },
      { id: 'hidrostatica', subjectId: 'fisica', name: 'Hidrostática', description: 'Pressão, densidade, empuxo e Princípio de Pascal/Arquimedes', order: 5, weight: 4 },
      { id: 'termologia_calor', subjectId: 'fisica', name: 'Termometria e Calorimetria', description: 'Escalas térmicas, calor sensível, latente e trocas de calor', order: 6, weight: 5 },
      { id: 'termodinamica', subjectId: 'fisica', name: 'Termodinâmica', description: '1ª e 2ª Leis, transformações gasosas e máquinas térmicas', order: 7, weight: 4 },
      { id: 'ondulatoria', subjectId: 'fisica', name: 'Ondulatória e Acústica', description: 'Equação fundamental, reflexão, refração, difração e Efeito Doppler', order: 8, weight: 5 },
      { id: 'optica_geometrica', subjectId: 'fisica', name: 'Óptica Geométrica', description: 'Espelhos planos/esféricos, lentes delgadas e refração', order: 9, weight: 4 },
      { id: 'eletrostatica', subjectId: 'fisica', name: 'Eletrostática', description: 'Carga elétrica, Lei de Coulomb e campo elétrico', order: 10, weight: 3 },
      { id: 'eletrodinamica', subjectId: 'fisica', name: 'Eletrodinâmica e Circuitos', description: 'Leis de Ohm, potência elétrica, resistores e geradores', order: 11, weight: 5 },
      { id: 'eletromagnetismo', subjectId: 'fisica', name: 'Magnetismo e Indução', description: 'Campo magnético, force magnética e Lei de Faraday', order: 12, weight: 4 },
      { id: 'fisica_moderna', subjectId: 'fisica', name: 'Física Moderna', description: 'Efeito fotoelétrico, relatividade restrita e fótons', order: 13, weight: 3 },
    ],
  },
  quimica: {
    id: 'quimica',
    name: 'Química',
    shortName: 'Quím',
    description: 'Estrutura atômica, estequiometria, físico-química e química orgânica.',
    category: 'exatas',
    color: 'emerald',
    accentColorHex: '#10B981',
    badgeBg: 'bg-emerald-500/10',
    badgeBorder: 'border-emerald-500/30',
    badgeText: 'text-emerald-400',
    gradient: 'from-emerald-500/20 via-teal-500/10 to-transparent',
    iconName: 'FlaskConical',
    topics: [
      { id: 'estrutura_atomica', subjectId: 'quimica', name: 'Estrutura Atômica e Tabela Periódica', description: 'Modelos atômicos, distribuição eletrônica e propriedades periódicas', order: 1, weight: 4 },
      { id: 'ligacoes_quimicas', subjectId: 'quimica', name: 'Ligações Químicas e Geometria', description: 'Iônica, covalente, metálica, polaridade e forças intermoleculares', order: 2, weight: 5 },
      { id: 'funcoes_inorganicas', subjectId: 'quimica', name: 'Funções Inorgânicas e Reações', description: 'Ácidos, bases, sais, óxidos e balanceamento', order: 3, weight: 4 },
      { id: 'estequiometria', subjectId: 'quimica', name: 'Estequiometria e Leis Ponderais', description: 'Massa molar, pureza, rendimento e reagente limitante', order: 4, weight: 5 },
      { id: 'solucoes_concentracao', subjectId: 'quimica', name: 'Soluções e Concentrações', description: 'Molaridade, título, solubilidade e diluição', order: 5, weight: 5 },
      { id: 'termoquimica', subjectId: 'quimica', name: 'Termoquímica', description: 'Entalpia, Lei de Hess, energia de ligação e combustão', order: 6, weight: 5 },
      { id: 'cinetica_quimica', subjectId: 'quimica', name: 'Cinética Química', description: 'Velocidade de reação, fatores e catalisadores', order: 7, weight: 4 },
      { id: 'equilibrio_quimico', subjectId: 'quimica', name: 'Equilíbrio Químico e pH', description: 'Kc, Kp, Le Chatelier, pH, pOH e hidrólise', order: 8, weight: 5 },
      { id: 'eletroquimica', subjectId: 'quimica', name: 'Eletroquímica (Pilhas e Eletrólise)', description: 'Potencial de redução, corrosão e leis de Faraday', order: 9, weight: 5 },
      { id: 'quimica_organica', subjectId: 'quimica', name: 'Química Orgânica e Funções', description: 'Hidrocarbonetos, álcoois, cetonas, ácidos carboxílicos e ésteres', order: 10, weight: 5 },
      { id: 'isomeria_polimeros', subjectId: 'quimica', name: 'Isomeria e Polímeros', description: 'Plana, espacial (óptica e geométrica), plásticos e biomoléculas', order: 11, weight: 4 },
      { id: 'quimica_ambiental', subjectId: 'quimica', name: 'Química Ambiental e Radioatividade', description: 'Chuva ácida, efeito estufa, decaimento e meia-vida', order: 12, weight: 4 },
    ],
  },
  biologia: {
    id: 'biologia',
    name: 'Biologia',
    shortName: 'Bio',
    description: 'Citologia, genética, ecologia, fisiologia humana, evolução e botânica.',
    category: 'biologicas',
    color: 'green',
    accentColorHex: '#22C55E',
    badgeBg: 'bg-green-500/10',
    badgeBorder: 'border-green-500/30',
    badgeText: 'text-green-400',
    gradient: 'from-green-500/20 via-lime-500/10 to-transparent',
    iconName: 'Dna',
    topics: [
      { id: 'citologia_bioquimica', subjectId: 'biologia', name: 'Citologia e Bioquímica Celular', description: 'Organelas, membrana plasmática, água, lipídios e proteínas', order: 1, weight: 5 },
      { id: 'metabolismo_energetico', subjectId: 'biologia', name: 'Metabolismo Energético', description: 'Fotossíntese, respiração celular, fermentação e ATP', order: 2, weight: 5 },
      { id: 'divisao_celular', subjectId: 'biologia', name: 'Divisão Celular e Dogma Central', description: 'Mitose, meiose, replicação, transcrição e tradução de DNA', order: 3, weight: 4 },
      { id: 'genetica_mendeliana', subjectId: 'biologia', name: 'Genética e Biotecnologia', description: '1ª e 2ª Leis de Mendel, heredogramas, transgênicos e CRISPR', order: 4, weight: 5 },
      { id: 'evolucao_biologica', subjectId: 'biologia', name: 'Evolução e Origem da Vida', description: 'Darwinismo, Lamarckismo, Neodarwinismo e especiação', order: 5, weight: 4 },
      { id: 'ecologia_biomas', subjectId: 'biologia', name: 'Ecologia e Impactos Ambientais', description: 'Cadeias alimentares, ciclos biogeoquímicos, biomas e desequilíbrios', order: 6, weight: 5 },
      { id: 'fisiologia_humana', subjectId: 'biologia', name: 'Fisiologia Humana e Saúde', description: 'Digestório, circulatório, respiratório, excretor e nervoso', order: 7, weight: 5 },
      { id: 'microbiologia_doencas', subjectId: 'biologia', name: 'Microbiologia, Vírus e Doenças', description: 'Bactérias, protozoários, fungos, vacinas e soros', order: 8, weight: 4 },
      { id: 'botanica', subjectId: 'biologia', name: 'Botânica e Fisiologia Vegetal', description: 'Grupos vegetais, tecidos, condução de seiva e fitormônios', order: 9, weight: 3 },
      { id: 'zoologia_embriologia', subjectId: 'biologia', name: 'Zoologia e Embriologia', description: 'Filos animais, folhetos embrionários e organogênese', order: 10, weight: 3 },
    ],
  },
  portugues: {
    id: 'portugues',
    name: 'Português & Gramática',
    shortName: 'Port',
    description: 'Sintaxe, concordância, regência, crase, morfologia, semântica e pontuação.',
    category: 'linguagens',
    color: 'rose',
    accentColorHex: '#F43F5E',
    badgeBg: 'bg-rose-500/10',
    badgeBorder: 'border-rose-500/30',
    badgeText: 'text-rose-400',
    gradient: 'from-rose-500/20 via-pink-500/10 to-transparent',
    iconName: 'BookOpen',
    topics: [
      { id: 'ortografia_acentuacao', subjectId: 'portugues', name: 'Ortografia e Acentuação', description: 'Novo acordo ortográfico, regras de acentuação e hífen', order: 1, weight: 4 },
      { id: 'morfologia_classes', subjectId: 'portugues', name: 'Morfologia e Classes de Palavras', description: 'Substantivo, adjetivo, pronome, verbo e conjunções', order: 2, weight: 5 },
      { id: 'sintaxe_periodo_simples', subjectId: 'portugues', name: 'Sintaxe: Termos da Oração', description: 'Sujeito, predicado, objetos, complementos e adjuntos', order: 3, weight: 5 },
      { id: 'sintaxe_periodo_composto', subjectId: 'portugues', name: 'Período Composto e Orações', description: 'Orações coordenadas e subordinadas substantivas/adjetivas/adverbiais', order: 4, weight: 5 },
      { id: 'concordancia_verbal_nominal', subjectId: 'portugues', name: 'Concordância Verbal e Nominal', description: 'Regras gerais, casos especiais e vozes verbais', order: 5, weight: 5 },
      { id: 'regencia_crase', subjectId: 'portugues', name: 'Regência e Uso da Crase', description: 'Regência verbal, nominal e regras de emprego da crase', order: 6, weight: 5 },
      { id: 'pontuacao_expressividade', subjectId: 'portugues', name: 'Pontuação e Efeitos de Sentido', description: 'Uso da vírgula, travessões, dois-pontos e estilo', order: 7, weight: 4 },
      { id: 'semantica_figuras', subjectId: 'portugues', name: 'Semântica e Figuras de Linguagem', description: 'Metáfora, metonímia, ironia, antítese, ambiguidade e polissemia', order: 8, weight: 5 },
      { id: 'funcoes_linguagem', subjectId: 'portugues', name: 'Funções da Linguagem e Variação', description: 'Emotiva, referencial, conativa, metalinguística e variedades regionais', order: 9, weight: 4 },
    ],
  },
  interpretacao: {
    id: 'interpretacao',
    name: 'Interpretação de Texto',
    shortName: 'Interp',
    description: 'Compreensão crítica, gêneros textuais, coesão, coerência e intertextualidade.',
    category: 'linguagens',
    color: 'indigo',
    accentColorHex: '#6366F1',
    badgeBg: 'bg-indigo-500/10',
    badgeBorder: 'border-indigo-500/30',
    badgeText: 'text-indigo-400',
    gradient: 'from-indigo-500/20 via-purple-500/10 to-transparent',
    iconName: 'FileText',
    topics: [
      { id: 'compreensao_interpretacao', subjectId: 'interpretacao', name: 'Compreensão vs Interpretação', description: 'Ideia central, inferências, pressupostos e subentendidos', order: 1, weight: 5 },
      { id: 'generos_tipologias', subjectId: 'interpretacao', name: 'Gêneros e Tipologias Textuais', description: 'Narrativo, dissertativo-argumentativo, injuntivo e crônicas', order: 2, weight: 5 },
      { id: 'coesao_coerencia', subjectId: 'interpretacao', name: 'Mecanismos de Coesão e Conectivos', description: 'Anáfora, catáfora, operadores argumentativos e progressão temática', order: 3, weight: 5 },
      { id: 'linguagem_nao_verbal', subjectId: 'interpretacao', name: 'Textos Multimodais e Imagens', description: 'Tirinhas, charges, infográficos, cartazes e propaganda', order: 4, weight: 5 },
      { id: 'intertextualidade', subjectId: 'interpretacao', name: 'Intertextualidade e Paródia', description: 'Citação, alusão, paráfrase e diálogo entre obras', order: 5, weight: 4 },
    ],
  },
  literatura: {
    id: 'literatura',
    name: 'Literatura Brasileira & Portuguesa',
    shortName: 'Lit',
    description: 'Escolas literárias, obras canônicas, autores fundamentais e modernismo.',
    category: 'linguagens',
    color: 'purple',
    accentColorHex: '#A855F7',
    badgeBg: 'bg-purple-500/10',
    badgeBorder: 'border-purple-500/30',
    badgeText: 'text-purple-400',
    gradient: 'from-purple-500/20 via-fuchsia-500/10 to-transparent',
    iconName: 'Feather',
    topics: [
      { id: 'quinhentismo_barroco_arcadismo', subjectId: 'literatura', name: 'Barroco e Arcadismo', description: 'Gregório de Matos, Pe. Vieira, Cláudio Manuel da Costa e Tomás Antônio Gonzaga', order: 1, weight: 4 },
      { id: 'romantismo', subjectId: 'literatura', name: 'Romantismo no Brasil (3 Gerações)', description: 'Nacionalismo, ultrarromantismo, condoreirismo (Gonçalves Dias, Álvares de Azevedo, Castro Alves)', order: 2, weight: 5 },
      { id: 'realismo_naturalismo', subjectId: 'literatura', name: 'Realismo, Naturalismo e Parnasianismo', description: 'Machado de Assis, Aluísio Azevedo e Olavo Bilac', order: 3, weight: 5 },
      { id: 'simbolismo_pre_modernismo', subjectId: 'literatura', name: 'Simbolismo e Pré-Modernismo', description: 'Cruz e Sousa, Euclides da Cunha, Lima Barreto e Monteiro Lobato', order: 4, weight: 4 },
      { id: 'modernismo_fase1', subjectId: 'literatura', name: 'Modernismo: 1ª Fase (Semana de 22)', description: 'Mário de Andrade, Oswald de Andrade e Manuel Bandeira', order: 5, weight: 5 },
      { id: 'modernismo_fase2', subjectId: 'literatura', name: 'Modernismo: 2ª Fase (Geração de 30)', description: 'Carlos Drummond de Andrade, Graciliano Ramos, Jorge Amado e Rachel de Queiroz', order: 6, weight: 5 },
      { id: 'modernismo_fase3_contemporanea', subjectId: 'literatura', name: '3ª Fase e Literatura Contemporânea', description: 'Clarice Lispector, Guimarães Rosa, João Cabral de Melo Neto e vozes atuais', order: 7, weight: 5 },
    ],
  },
  historia: {
    id: 'historia',
    name: 'História Geral & do Brasil',
    shortName: 'Hist',
    description: 'História antiga, moderna, contemporânea, Brasil Colônia, Império e República.',
    category: 'humanas',
    color: 'red',
    accentColorHex: '#EF4444',
    badgeBg: 'bg-red-500/10',
    badgeBorder: 'border-red-500/30',
    badgeText: 'text-red-400',
    gradient: 'from-red-500/20 via-orange-500/10 to-transparent',
    iconName: 'Landmark',
    topics: [
      { id: 'antiguidade_greco_romana', subjectId: 'historia', name: 'Antiguidade Clássica (Grécia e Roma)', description: 'Democracia ateniense, República, Império Romano e cidadania', order: 1, weight: 4 },
      { id: 'idade_media_feudalismo', subjectId: 'historia', name: 'Idade Média e Sistema Feudal', description: 'Igreja Católica, Cruzadas, renascimento comercial e peste negra', order: 2, weight: 4 },
      { id: 'idade_moderna_absolutismo', subjectId: 'historia', name: 'Idade Moderna e Expansão Marítima', description: 'Renascimento, Reforma Protestante, Absolutismo e Mercantilismo', order: 3, weight: 4 },
      { id: 'brasil_colonia', subjectId: 'historia', name: 'Brasil Colônia (1500-1822)', description: 'Capitanias, cana-de-açúcar, mineração, escravidão e rebeliões', order: 4, weight: 5 },
      { id: 'revolucoes_burguesas', subjectId: 'historia', name: 'Iluminismo e Revoluções', description: 'Revolução Francesa, Industrial e Independência dos EUA', order: 5, weight: 5 },
      { id: 'brasil_imperio', subjectId: 'historia', name: 'Brasil Império (1º, Regência e 2º Reinado)', description: 'Constituição de 1824, café, Guerra do Paraguai e abolição', order: 6, weight: 5 },
      { id: 'brasil_republica_velha', subjectId: 'historia', name: 'República Oligárquica e Era Vargas', description: 'Café com leite, coronelismo, revoluções de 30 e Estado Novo', order: 7, weight: 5 },
      { id: 'guerras_mundiais_totalitarismo', subjectId: 'historia', name: 'Guerras Mundiais e Nazifascismo', description: 'Primeira e Segunda Guerra Mundial, Holocausto e descolonização', order: 8, weight: 5 },
      { id: 'guerra_fria_contemporanea', subjectId: 'historia', name: 'Guerra Fria e Geopolítica do Século XX', description: 'EUA vs URSS, corrida armamentista, Queda do Muro e globalização', order: 9, weight: 5 },
      { id: 'brasil_ditadura_redemocratizacao', subjectId: 'historia', name: 'Ditadura Militar e Nova República', description: 'Golpe de 64, AI-5, Diretas Já, Constituição de 88 e atualidades', order: 10, weight: 5 },
    ],
  },
  geografia: {
    id: 'geografia',
    name: 'Geografia Geral & do Brasil',
    shortName: 'Geo',
    description: 'Cartografia, climatologia, relevo, geopolítica, urbanização, demografia e meio ambiente.',
    category: 'humanas',
    color: 'teal',
    accentColorHex: '#14B8A6',
    badgeBg: 'bg-teal-500/10',
    badgeBorder: 'border-teal-500/30',
    badgeText: 'text-teal-400',
    gradient: 'from-teal-500/20 via-emerald-500/10 to-transparent',
    iconName: 'Globe2',
    topics: [
      { id: 'cartografia_escalas', subjectId: 'geografia', name: 'Cartografia e Fusos Horários', description: 'Projeções cartográficas, curvas de nível, escalas e coordenadas', order: 1, weight: 4 },
      { id: 'geografia_fisica_relevo', subjectId: 'geografia', name: 'Geomorfologia, Relevo e Solos', description: 'Tectônica de placas, vulcanismo, agentes do relevo e intemperismo', order: 2, weight: 4 },
      { id: 'climatologia_hidrografia', subjectId: 'geografia', name: 'Climatologia e Recursos Hídricos', description: 'Fatores climáticos, massas de ar, bacias hidrográficas e crises hídricas', order: 3, weight: 5 },
      { id: 'biomas_vegetacao', subjectId: 'geografia', name: 'Biomas Brasileiros e Mundiais', description: 'Amazônia, Cerrado, Mata Atlântica, Caatinga, Pampa e Pantanal', order: 4, weight: 5 },
      { id: 'demografia_populacao', subjectId: 'geografia', name: 'Demografia e Fluxos Migratórios', description: 'Transição demográfica, pirâmides etárias e migrações', order: 5, weight: 4 },
      { id: 'urbanizacao_industrializacao', subjectId: 'geografia', name: 'Urbanização e Industrialização', description: 'Metropolização, segregação socioespacial e revoluções industriais', order: 6, weight: 5 },
      { id: 'geopolitica_globalizacao', subjectId: 'geografia', name: 'Geopolítica e Globalização', description: 'Blocos econômicos, conflitos internacionais e nova ordem mundial', order: 7, weight: 5 },
      { id: 'agropecuaria_energia', subjectId: 'geografia', name: 'Agropecuária, Energia e Mineração', description: 'Agronegócio, matriz energética e sustentabilidade', order: 8, weight: 5 },
    ],
  },
  ingles: {
    id: 'ingles',
    name: 'Língua Inglesa',
    shortName: 'Ing',
    description: 'Interpretação textual, conectivos, vocabulário acadêmico e falsos cognatos.',
    category: 'linguagens',
    color: 'blue',
    accentColorHex: '#3B82F6',
    badgeBg: 'bg-blue-500/10',
    badgeBorder: 'border-blue-500/30',
    badgeText: 'text-blue-400',
    gradient: 'from-blue-500/20 via-indigo-500/10 to-transparent',
    iconName: 'Languages',
    topics: [
      { id: 'skimming_scanning', subjectId: 'ingles', name: 'Técnicas de Leitura: Skimming & Scanning', description: 'Leitura rápida para ideia geral e busca de informações específicas', order: 1, weight: 5 },
      { id: 'linking_words', subjectId: 'ingles', name: 'Linking Words & Conectivos', description: 'However, although, furthermore, therefore, despite e relações lógicas', order: 2, weight: 5 },
      { id: 'false_friends_vocab', subjectId: 'ingles', name: 'Vocabulário e Falsos Cognatos', description: 'Pretend, actually, eventually, notice e termos vestibulares', order: 3, weight: 5 },
      { id: 'verb_tenses_modals', subjectId: 'ingles', name: 'Tempos Verbais e Modal Verbs', description: 'Present Perfect, Passive Voice, Should, Must, Could, Might', order: 4, weight: 4 },
      { id: 'textual_reference', subjectId: 'ingles', name: 'Referência Textual e Pronomes', description: 'Identificação de antecedentes (it, they, which, whom) no texto', order: 5, weight: 4 },
    ],
  },
  filosofia: {
    id: 'filosofia',
    name: 'Filosofia',
    shortName: 'Filo',
    description: 'Ética, política, epistemologia, filosofia antiga, moderna e contemporânea.',
    category: 'humanas',
    color: 'violet',
    accentColorHex: '#8B5CF6',
    badgeBg: 'bg-violet-500/10',
    badgeBorder: 'border-violet-500/30',
    badgeText: 'text-violet-400',
    gradient: 'from-violet-500/20 via-purple-500/10 to-transparent',
    iconName: 'Lightbulb',
    topics: [
      { id: 'filosofia_antiga_grega', subjectId: 'filosofia', name: 'Filosofia Antiga: Sócrates, Platão e Aristóteles', description: 'Mito vs Razão, Teoria das Ideias, Ética a Nicômaco e Política', order: 1, weight: 5 },
      { id: 'filosofia_medieval', subjectId: 'filosofia', name: 'Filosofia Medieval: Patrística e Escolástica', description: 'Santo Agostinho (Fé e Razão) e São Tomás de Aquino', order: 2, weight: 3 },
      { id: 'filosofia_moderna_contratualismo', subjectId: 'filosofia', name: 'Contratualismo e Política Moderna', description: 'Maquiavel, Hobbes, Locke, Rousseau e Montesquieu', order: 3, weight: 5 },
      { id: 'epistemologia_racionalismo_empirismo', subjectId: 'filosofia', name: 'Teoria do Conhecimento: Descartes e Kant', description: 'Racionalismo cartesiano, empirismo de Hume e criticismo kantiano', order: 4, weight: 5 },
      { id: 'filosofia_contemporanea', subjectId: 'filosofia', name: 'Filosofia Contemporânea e Ética', description: 'Nietzsche, Foucault, Escola de Frankfurt, Sartre e Habermas', order: 5, weight: 5 },
    ],
  },
  sociologia: {
    id: 'sociologia',
    name: 'Sociologia',
    shortName: 'Soc',
    description: 'Clássicos da sociologia, cultura, estado, desigualdades, trabalho e cidadania.',
    category: 'humanas',
    color: 'pink',
    accentColorHex: '#EC4899',
    badgeBg: 'bg-pink-500/10',
    badgeBorder: 'border-pink-500/30',
    badgeText: 'text-pink-400',
    gradient: 'from-pink-500/20 via-rose-500/10 to-transparent',
    iconName: 'Users2',
    topics: [
      { id: 'sociologia_classica', subjectId: 'sociologia', name: 'Clássicos: Durkheim, Marx e Weber', description: 'Fato social, mais-valia, luta de classes, ação social e burocracia', order: 1, weight: 5 },
      { id: 'cultura_identidade', subjectId: 'sociologia', name: 'Cultura, Etnocentrismo e Diversidade', description: 'Indústria cultural, patrimônio, etnocentrismo e relativismo cultural', order: 2, weight: 5 },
      { id: 'desigualdade_estratificacao', subjectId: 'sociologia', name: 'Estratificação Social e Desigualdades', description: 'Classes sociais, mobilidade, gênero, raça e inclusão', order: 3, weight: 5 },
      { id: 'estado_politica_cidadania', subjectId: 'sociologia', name: 'Estado, Poder, Democracia e Cidadania', description: 'Direitos civis, políticos e sociais, movimentos sociais e participação', order: 4, weight: 5 },
      { id: 'mundo_trabalho', subjectId: 'sociologia', name: 'Mundo do Trabalho e Globalização', description: 'Taylorismo, Fordismo, Toyotismo, precarização e uberização', order: 5, weight: 4 },
    ],
  },
  redacao: {
    id: 'redacao',
    name: 'Redação & Repertório',
    shortName: 'Red',
    description: 'Estrutura dissertativa, tese, repertórios socioculturais e proposta de intervenção.',
    category: 'linguagens',
    color: 'orange',
    accentColorHex: '#F97316',
    badgeBg: 'bg-orange-500/10',
    badgeBorder: 'border-orange-500/30',
    badgeText: 'text-orange-400',
    gradient: 'from-orange-500/20 via-amber-500/10 to-transparent',
    iconName: 'PenTool',
    topics: [
      { id: 'estrutura_dissertativa', subjectId: 'redacao', name: 'Estrutura Dissertativo-Argumentativa', description: 'Introdução com tese, desenvolvimento (D1/D2) e conclusão', order: 1, weight: 5 },
      { id: 'repertorio_legitimado', subjectId: 'redacao', name: 'Repertório Sociocultural e Filosófico', description: 'Filósofos, sociólogos, dados estatísticos, história e literatura', order: 2, weight: 5 },
      { id: 'proposta_intervencao_enem', subjectId: 'redacao', name: 'Proposta de Intervenção Completa (ENEM)', description: '5 elementos: Agente, Ação, Meio/Modo, Efeito e Detalhamento', order: 3, weight: 5 },
      { id: 'competencias_avaliacao', subjectId: 'redacao', name: 'Competências de Correção (ENEM / FUVEST / FATEC)', description: 'Norma culta, tema, argumentação, coesão e direitos humanos', order: 4, weight: 4 },
    ],
  },
  atualidades: {
    id: 'atualidades',
    name: 'Atualidades & Conhecimentos Gerais',
    shortName: 'Atual',
    description: 'Acontecimentos recentes, economia global, avanços científicos e debates públicos.',
    category: 'humanas',
    color: 'sky',
    accentColorHex: '#0EA5E9',
    badgeBg: 'bg-sky-500/10',
    badgeBorder: 'border-sky-500/30',
    badgeText: 'text-sky-400',
    gradient: 'from-sky-500/20 via-cyan-500/10 to-transparent',
    iconName: 'Newspaper',
    topics: [
      { id: 'geopolitica_atual', subjectId: 'atualidades', name: 'Geopolítica e Conflitos Contemporâneos', description: 'Oriente Médio, Guerra na Ucrânia, tensões EUA-China e BRICS', order: 1, weight: 5 },
      { id: 'meio_ambiente_clima', subjectId: 'atualidades', name: 'Crise Climática e Transição Energética', description: 'Acordo de Paris, COPs, fontes renováveis e descarbonização', order: 2, weight: 5 },
      { id: 'tecnologia_ia_sociedade', subjectId: 'atualidades', name: 'Inteligência Artificial e Transformação Digital', description: 'Impactos no trabalho, ética, privacidade e desinformação', order: 3, weight: 4 },
      { id: 'sociedade_saude_publica', subjectId: 'atualidades', name: 'Debates Sociais e Saúde Global', description: 'Epidemias, demografia, polarização e segurança alimentar', order: 4, weight: 4 },
    ],
  },
  raciocinio_logico: {
    id: 'raciocinio_logico',
    name: 'Raciocínio Lógico',
    shortName: 'Lógica',
    description: 'Proposições, tabelas-verdade, argumentos válidos, sequências e diagramas lógicos.',
    category: 'exatas',
    color: 'emerald',
    accentColorHex: '#059669',
    badgeBg: 'bg-emerald-500/10',
    badgeBorder: 'border-emerald-500/30',
    badgeText: 'text-emerald-400',
    gradient: 'from-emerald-500/20 via-teal-500/10 to-transparent',
    iconName: 'BrainCircuit',
    topics: [
      { id: 'proposicoes_conectivos', subjectId: 'raciocinio_logico', name: 'Lógica Proposicional e Conectivos', description: 'Negação, conjunção (E), disjunção (OU), condicional (Se... então)', order: 1, weight: 5 },
      { id: 'tabelas_verdade_equivalencias', subjectId: 'raciocinio_logico', name: 'Tabelas-Verdade e Leis de De Morgan', description: 'Tautologia, contradição e equivalências lógicas fundamentais', order: 2, weight: 5 },
      { id: 'diagramas_quantificadores', subjectId: 'raciocinio_logico', name: 'Diagramas Lógicos e Conjuntos', description: 'Todo, algum, nenhum e interseções lógicas', order: 3, weight: 4 },
      { id: 'sequencias_padroes', subjectId: 'raciocinio_logico', name: 'Sequências Lógicas e Padrões Numéricos', description: 'Identificação de padrões visuais, numéricos e temporais', order: 4, weight: 4 },
    ],
  },
};

export const ALL_SUBJECT_IDS = Object.keys(SUBJECTS_CONFIG) as SubjectId[];

export const SUBJECT_CATEGORIES: { id: SubjectCategory; label: string; icon: string }[] = [
  { id: 'all', label: 'Todas as Áreas', icon: 'Sparkles' },
  { id: 'exatas', label: 'Exatas & Lógica', icon: 'Calculator' },
  { id: 'humanas', label: 'Humanas & Sociais', icon: 'Globe' },
  { id: 'biologicas', label: 'Biológicas & Saúde', icon: 'Dna' },
  { id: 'linguagens', label: 'Linguagens & Redação', icon: 'BookOpen' },
];

export function getSubjectConfig(subjectId: SubjectId | string): SubjectDefinition {
  return SUBJECTS_CONFIG[subjectId as SubjectId] || SUBJECTS_CONFIG.matematica;
}

export function getAllSubjectsList(): SubjectDefinition[] {
  return Object.values(SUBJECTS_CONFIG);
}

export function getSubjectsByCategory(category: SubjectCategory): SubjectDefinition[] {
  const all = getAllSubjectsList();
  if (category === 'all') return all;
  return all.filter((s) => s.category === category);
}
